const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const P=require('../platform/parent-portal-model.js');
const base=process.argv[2]||'http://127.0.0.1:8765/platform/index.html';
const out=process.env.OPS_SCREENSHOTS||'C:/Users/USER/.codex/visualizations/2026/06/15/019ec9d5-ff53-7d50-b6cc-5252e07856c3';
const admin={id:'admin',name:'CRM 관리자',email:'admin@example.com',role:'admin'},staff={id:'staff',name:'김 담당',email:'staff@example.com',role:'staff'},parent={id:'parent',name:'테스트 보호자',email:'parent@example.com',role:'parent'};
const expires=Math.floor(Date.now()/1000)+3600,jwt=u=>[Buffer.from('{}').toString('base64url'),Buffer.from(JSON.stringify({sub:u.id,exp:expires})).toString('base64url'),'test'].join('.');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});let page;const errors=[];
 try{
  const ctx=await browser.newContext({viewport:{width:1440,height:1000}});ctx.setDefaultTimeout(20000);page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'?portal=staff');await page.getByRole('heading',{name:'직원 로그인'}).waitFor({timeout:60000});
  const fixture=await page.evaluate(()=>{
   const make=(id,name,program,owner)=>v2NormalizeStudent({...blankStudent(),id,name,en:'',program,owners:[owner],owner,school:'Phillips Exeter Academy',currentGrade:'8학년',stage:'stage1',ecs:[],tests:[],awards:[],academicTerms:[],actionPlans:[],tasks:[],applications:[],calendarEvents:[],operations:{},programEndDate:'2027-06-30'});
   const a=make('a','가 학생','시니어보딩','admin'),b=make('b','나 학생','보딩프렙','staff');a.basic.dob='2012-01-01';b.basic.dob='2013-01-01';a.parentPortal={...PrepParentModel.normalize(a),enabled:true};b.parentPortal={...PrepParentModel.normalize(b),enabled:true,submissions:[{id:'submission-b',status:'submitted',submittedAt:'2026-09-16T00:00:00Z',profile:PrepParentModel.pickProfile(b),declarations:{},baseProfile:PrepParentModel.pickProfile(b)}]};
   return {students:[a,b],schools:PREP_SCHOOLS};
  });
  const versions={a:1,b:1,__schools:1};let workspace={events:[],tasks:[],subscriptions:{},crmViews:[]},workspaceVersion=0;
  const attach=async context=>{
   await context.route('**/auth/v1/**',async route=>{if(route.request().url().includes('/logout'))return route.fulfill({status:204});const body=route.request().postDataJSON()||{},u=body.email===parent.email?parent:body.email===staff.email?staff:admin;return route.fulfill({json:{access_token:jwt(u),refresh_token:'test',token_type:'bearer',expires_in:3600,user:u}});});
   await context.route('**/functions/v1/prep-portal',async route=>{
    const body=route.request().postDataJSON(),token=route.request().headers().authorization,u=token==='Bearer '+jwt(parent)?parent:token==='Bearer '+jwt(staff)?staff:admin;let result;
    if(body.action==='load')result={user:u,students:u.role==='parent'?[P.publicStudent(fixture.students[0])]:u.role==='staff'?fixture.students.filter(s=>s.owners.includes(u.id)):fixture.students,schools:fixture.schools,staffAccounts:[admin,staff],workspace:u.role==='admin'?workspace:{},workspaceVersion:u.role==='admin'?workspaceVersion:0,versions,teamEvents:[],sharedCalendar:[]};
    else if(body.action==='revisions')result={versions,workspaceVersion};
    else if(body.action==='saveWorkspace'){assert.equal(body.version,workspaceVersion);workspace=body.payload;result={payload:workspace,version:++workspaceVersion};}
    else if(body.action==='save'){for(const c of body.changes){assert.equal(c.expectedVersion,versions[c.id]||0);if(c.kind==='student')fixture.students=fixture.students.map(s=>s.id===c.id?c.payload:s);versions[c.id]=(versions[c.id]||0)+1;}result={versions};}
    else if(body.action==='requestReply'){assert.equal(u.role,'parent');assert.equal(body.studentId,'a');assert.equal(body.version,versions.a);fixture.students[0].parentPortal=P.replyToRequest(fixture.students[0],body.requestId,body.reply);versions.a++;result={student:P.publicStudent(fixture.students[0]),versions};}
    else if(body.action==='accounts')result={members:[],invitations:[]};else throw Error('Unexpected action '+body.action);
    return route.fulfill({json:result});
   });
  };
  await attach(ctx);
  const button=(name,scope=page)=>scope.getByRole('button',{name,exact:true}),dialog=()=>page.getByRole('dialog');
  const saveWait=()=>page.getByText('공용 저장 완료',{exact:true}).waitFor();
  const login=async(p,u)=>{await p.getByLabel('이메일',{exact:true}).fill(u.email);await p.getByLabel('비밀번호',{exact:true}).fill('test-password-only');await p.getByRole('button',{name:'로그인',exact:true}).click();await p.getByRole('button',{name:'로그아웃',exact:true}).waitFor();};
  await login(page,admin);
  await button('학생 관리').click();await page.getByText('상세 필터',{exact:true}).click();await page.getByLabel('프로그램 필터').selectOption('시니어보딩');assert.equal(await button('열기').count(),1);
  await page.getByText('내 필터 보기',{exact:true}).click();await page.getByLabel('필터 이름').fill('시니어 학생');await button('현재 필터 저장').click();await saveWait();assert.equal(workspace.crmViews.length,1);
  await page.getByLabel('프로그램 필터').selectOption('');await page.getByLabel('저장된 필터').selectOption(workspace.crmViews[0].id);assert.equal(await button('열기').count(),1);
  await page.getByLabel('프로그램 필터').selectOption('');await page.getByLabel('현재 표시 학생 전체 선택').check();await button('일괄 작업').click();await dialog().getByLabel('일괄 업무명 *').fill('학기 자료 점검');await dialog().getByLabel('일괄 업무 기한 *').fill('2026-10-01');await button('학생별 업무 등록',dialog()).click();await saveWait();assert(fixture.students.every(s=>s.tasks.some(t=>t.title==='학기 자료 점검')));
  await page.screenshot({path:out+'/crm-directory-desktop.png'});
  await page.getByLabel('학생·학교·태그 검색').fill('가 학생');await button('연락 관리').click();await button('연락 기록').click();await dialog().getByLabel('연락 내용 *').fill('학부모와 학기별 목표를 합의했습니다. 내부 연락 메모.');await dialog().getByLabel('다음에 할 일').fill('검토한 목표 안내');await dialog().getByLabel('후속 기한 *').fill('2026-09-24');await button('연락 기록과 후속 업무 저장',dialog()).click();await saveWait();assert.equal(fixture.students[0].operations.crm.contacts.length,1);assert(fixture.students[0].tasks.some(t=>t.title==='검토한 목표 안내'));
  await button('체크리스트').click();await button('업무에 추가',dialog()).click();await saveWait();assert.equal(fixture.students[0].tasks.filter(t=>t.templateKey).length,4);
  await button('관리 설정').click();await dialog().getByLabel('관리 우선순위').selectOption('high');await dialog().getByLabel('정기 연락 주기').selectOption('7');await dialog().getByLabel('인수인계 메모 (내부)').fill('내부 인수인계: 다음 상담에서 일정 확인');await button('저장',dialog()).click();await saveWait();assert.equal(fixture.students[0].operations.crm.cadence,7);
  await page.screenshot({path:out+'/crm-student-desktop.png'});
  await button('자료 요청').click();await button('자료 요청 추가').click();await dialog().getByLabel('요청 자료명 *').fill('Fall 성적표 제출');await dialog().getByLabel('자료 제출 기한 *').fill('2026-10-01');await dialog().getByLabel('학부모 안내 내용').fill('학교에서 발급받은 성적표 링크를 제출해 주세요.');await button('학부모 포털에 요청 등록',dialog()).click();await saveWait();assert.equal(fixture.students[0].parentPortal.requests.length,1);
  await button('캘린더').click();await page.getByLabel('캘린더 월',{exact:true}).fill('2026-10');await page.locator('.ops-cal').getByRole('button',{name:'가 학생 · 자료 회신 · Fall 성적표 제출',exact:true}).click();await button('자료 요청 추가').waitFor();
  await button('CRM 관리').click();await button('통합 업무').click();await page.getByLabel('업무 검색').fill('검토한 목표 안내');await button('완료 처리').click();await saveWait();assert(fixture.students[0].tasks.find(t=>t.title==='검토한 목표 안내').done);await page.getByLabel('업무 상태 필터').selectOption('done');await button('완료 취소').waitFor();
  await button('담당자별 업무 현황').click();await page.getByRole('heading',{name:'담당자별 업무 현황'}).waitFor();await page.screenshot({path:out+'/crm-workload.png'});
  await button('확인 목록').click();const row=page.locator('.crm-alert-row').filter({hasText:'학부모 자료 검토'});await row.getByRole('button',{name:'확인하기'}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('select')).some(s=>s.value==='b'));await page.getByText('나 학생 · 학부모 연결',{exact:true}).waitFor();
  await button('학생 관리').click();await page.getByLabel('학생·학교·태그 검색').fill('가 학생');await page.locator('.crm-students').getByLabel('가 학생 선택',{exact:true}).check();await button('일괄 작업').click();await dialog().getByLabel('일괄 작업 종류').selectOption('owners');await dialog().getByLabel('김 담당',{exact:true}).check();await dialog().getByLabel('학생 명단과 담당자 접근 권한 변경을 확인했습니다').check();await button('담당자 변경 적용',dialog()).click();await saveWait();assert.deepEqual(fixture.students[0].owners,['staff']);
  await button('연락 관리').click();await button('관리 설정').click();await dialog().getByLabel('CRM 관리 상태').selectOption('completed');await button('저장',dialog()).click();await saveWait();await button('학생 관리').click();assert.equal(await button('열기').count(),1);await page.getByLabel('관리 상태 필터').selectOption('completed');assert.equal(await button('열기').count(),1);await button('연락 관리').click();await button('관리 설정').click();await dialog().getByLabel('CRM 관리 상태').selectOption('active');await button('저장',dialog()).click();await saveWait();
  await button('학생 관리').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/crm-directory-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.crm-mobile-students .ops-item').count(),2);
  const sctx=await browser.newContext();sctx.setDefaultTimeout(20000);await attach(sctx);const sp=await sctx.newPage();sp.on('pageerror',e=>errors.push(e.message));await sp.goto(base+'?portal=staff');await login(sp,staff);await sp.getByRole('button',{name:'CRM 관리',exact:true}).click();assert.equal(await sp.getByRole('button',{name:'담당자별 업무 현황',exact:true}).count(),0);
  const pctx=await browser.newContext();pctx.setDefaultTimeout(20000);await attach(pctx);const pp=await pctx.newPage();pp.on('pageerror',e=>errors.push(e.message));await pp.goto(base+'?portal=parent');await login(pp,parent);assert.equal(await pp.getByRole('button',{name:'CRM 관리',exact:true}).count(),0);assert(!(await pp.locator('body').innerText()).includes('내부 연락 메모'));assert(!JSON.stringify(P.publicStudent(fixture.students[0])).includes('내부 인수인계'));
  await pp.getByRole('button',{name:'요청 자료',exact:true}).click();await pp.getByRole('button',{name:'자료 / 답변 제출',exact:true}).click();await pp.getByLabel('자료 링크',{exact:true}).fill('https://example.com/report.pdf');await pp.getByLabel('전달 내용',{exact:true}).fill('학교 발급 자료입니다.');await pp.getByRole('button',{name:'검토 요청 제출',exact:true}).click();await pp.getByText('검토 대기',{exact:true}).waitFor();assert.equal(fixture.students[0].parentPortal.requests[0].status,'submitted');
  await page.setViewportSize({width:1440,height:1000});await page.reload();await button('학생 관리').click();await page.getByLabel('학생·학교·태그 검색').fill('가 학생');await button('연락 관리').click();await button('자료 요청').click();await button('회신 검토').click();await dialog().getByLabel('검토 안내 / 보완 요청 사유').fill('뒷면도 함께 제출해 주세요.');await button('보완 요청',dialog()).click();await saveWait();assert.equal(fixture.students[0].parentPortal.requests[0].status,'returned');
  await pp.reload();await pp.getByRole('button',{name:'요청 자료',exact:true}).click();await pp.getByText('담당자 안내: 뒷면도 함께 제출해 주세요.',{exact:true}).waitFor();await pp.getByRole('button',{name:'자료 / 답변 제출',exact:true}).click();await pp.getByLabel('전달 내용',{exact:true}).fill('뒷면 포함 자료로 보완했습니다.');await pp.getByLabel('자료 링크',{exact:true}).fill('https://example.com/report-complete.pdf');await pp.getByRole('button',{name:'검토 요청 제출',exact:true}).click();await pp.getByText('검토 대기',{exact:true}).waitFor();assert.equal(fixture.students[0].parentPortal.requests[0].replies.length,2);await pp.screenshot({path:out+'/crm-family-requests.png'});
  await page.reload();await button('학생 관리').click();await page.getByLabel('학생·학교·태그 검색').fill('가 학생');await button('연락 관리').click();await button('자료 요청').click();await button('회신 검토').click();await button('확인 완료',dialog()).click();await saveWait();assert.equal(fixture.students[0].parentPortal.requests[0].status,'accepted');await page.getByLabel('완료 / 취소 포함',{exact:true}).check();await page.getByText('확인 완료',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);console.log('PASS CRM E2E: saved filters, scoped bulk tasks, contact followups, checklists, timeline, task completion, workload, correct family-review deep link, admin assignment, archive/restore, responsive directory, consultant and family permissions, material request/reply/return/resubmit/accept. No production writes.');
 }catch(e){if(page){console.error((await page.locator('body').innerText()).slice(-3000));await page.screenshot({path:out+'/crm-test-failure.png'});}throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
