const CRM_REQUEST_STATUS={requested:'자료 요청',submitted:'검토 대기',accepted:'확인 완료',returned:'보완 요청',cancelled:'요청 취소'};
const CRM_REQUEST_CATEGORIES=['기본 정보','학교 정보','성적표','시험 결과','EC 활동','수상','원서 서류','기타'];
function CRMRequestHistory({request:r}){return <>{r.reply&&<div className="ops-log"><b>학부모 회신 · {ppTime(r.reply.submittedAt)}</b><p className="crm-prewrap">{r.reply.note}</p><OpsLink url={r.reply.url}>첨부 자료 열기</OpsLink></div>}{r.reviewNote&&<p className="ops-notice">담당자 안내: {r.reviewNote}</p>}{(r.replies||[]).length>1&&<details><summary>이전 회신 {(r.replies||[]).length-1}건</summary>{r.replies.slice(0,-1).map((v,i)=><div key={v.id||i} className="ops-log"><time>{ppTime(v.submittedAt)}</time><p className="crm-prewrap">{v.note}</p><OpsLink url={v.url}>자료 열기</OpsLink></div>)}</details>}{(r.reviews||[]).length>0&&<details><summary>검토 이력 {r.reviews.length}건</summary>{r.reviews.map((v,i)=><div className="ops-log" key={i}><b>{CRM_REQUEST_STATUS[v.status]} · {ppTime(v.at)}</b><p>{v.authorName}</p><p className="crm-prewrap">{v.note}</p></div>)}</details>}</>;}
function CRMRequestEditor({st,update,user,close}){
  const [d,setD]=useState({id:O.id(),title:'',category:'성적표',dueDate:O.addDays(O.today(),7),instructions:'',status:'requested'}),set=(k,v)=>setD({...d,[k]:v});
  return <PPDialog title="학부모 자료 요청" close={close}><div className="ops"><OpsField label="요청 자료명 *" value={d.title} onChange={v=>set('title',v)}/><div className="ops-grid"><OpsField label="자료 종류" value={d.category} options={CRM_REQUEST_CATEGORIES} onChange={v=>set('category',v)}/><OpsField label="자료 제출 기한 *" type="date" value={d.dueDate} onChange={v=>set('dueDate',v)}/></div><OpsField label="학부모 안내 내용" type="textarea" value={d.instructions} onChange={v=>set('instructions',v)}/><OpsSave run={()=>{if(!d.title.trim()||!O.date(d.dueDate))throw Error('자료명과 기한을 입력해 주세요.');const p=PP.normalize(st);if(!p.enabled)throw Error('학부모 포털을 활성화한 후 요청해 주세요.');const now=new Date().toISOString();return update({parentPortal:{...p,requests:[{...d,authorName:user.name,authorId:user.id,createdAt:now},...(p.requests||[])],updates:[{id:d.id,at:now,title:'자료 요청',detail:d.title+' · '+d.dueDate},...p.updates]}});}} onDone={close}>학부모 포털에 요청 등록</OpsSave></div></PPDialog>;
}
function CRMRequests({st,update,user}){
  const p=PP.normalize(st),[create,setCreate]=useState(false),[review,setReview]=useState(null),[note,setNote]=useState(''),[showClosed,setShowClosed]=useState(false);
  const requests=(p.requests||[]).filter(r=>showClosed||!['accepted','cancelled'].includes(r.status));
  const finish=status=>{if(status==='returned'&&!note.trim())throw Error('보완 요청 사유를 입력해 주세요.');const now=new Date().toISOString();return update({parentPortal:{...p,requests:p.requests.map(r=>r.id===review.id?{...r,status,reviewNote:note,reviewedAt:now,reviewedBy:user.name}:r),updates:[{id:'request-review-'+review.id+'-'+now,at:now,title:status==='accepted'?'요청 자료 확인 완료':'요청 자료 보완 안내',detail:review.title},...p.updates]},operations:O.recordUpdate(st,'요청 자료 검토',review.title)});};
  return <div className="ops"><div className="ops-toolbar"><h2>학부모 요청 자료</h2><OpsCheck label="완료 / 취소 포함" value={showClosed} onChange={setShowClosed}/><OpsButton icon="FilePlus2" onClick={()=>setCreate(true)}>자료 요청 추가</OpsButton></div>{!p.enabled&&<p className="ops-notice">학부모 포털이 비활성화되어 있습니다. 계정을 연결하고 포털을 활성화해 주세요.</p>}{requests.map(r=><article className="ops-item" key={r.id}><div className="ops-toolbar"><h3>{r.title}</h3><span className="ops-tag">{CRM_REQUEST_STATUS[r.status]}</span></div><p>{r.category} · {r.dueDate} {!['accepted','cancelled'].includes(r.status)&&<OpsDeadline date={r.dueDate}/>}</p><p className="crm-prewrap">{r.instructions}</p><CRMRequestHistory request={r}/><div className="ops-toolbar">{r.status==='submitted'&&<OpsButton icon="ClipboardCheck" onClick={()=>{setReview(r);setNote('');}}>회신 검토</OpsButton>}{r.status!=='cancelled'&&<OpsSave run={()=>{if(!confirm('이 자료 요청을 취소할까요? 회신 기록은 보존됩니다.'))return;return update({parentPortal:{...p,requests:p.requests.map(x=>x.id===r.id?{...x,status:'cancelled'}:x)}});}}>요청 취소</OpsSave>}</div></article>)}{!requests.length&&<OpsEmpty>진행 중인 자료 요청이 없습니다.</OpsEmpty>}{create&&<CRMRequestEditor st={st} update={update} user={user} close={()=>setCreate(false)}/>} {review&&<PPDialog title={review.title+' 검토'} close={()=>setReview(null)}><div className="ops"><CRMRequestHistory request={review}/><OpsField label="검토 안내 / 보완 요청 사유" type="textarea" value={note} onChange={setNote}/><div className="ops-toolbar"><OpsSave run={()=>finish('accepted')} onDone={()=>setReview(null)}>확인 완료</OpsSave><OpsSave run={()=>finish('returned')} onDone={()=>setReview(null)}>보완 요청</OpsSave></div></div></PPDialog>}</div>;
}
function CRMFamilyRequests({students,replyRequest,onDirty,preview=false}){
  const [reply,setReply]=useState(null),[note,setNote]=useState(''),[url,setUrl]=useState(''),[error,setError]=useState('');
  const requests=students.flatMap(s=>(s.parentPortal.requests||[]).map(r=>({...r,student:s}))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const close=()=>{if((note||url)&&!confirm('작성 중인 회신을 닫을까요?'))return;setReply(null);onDirty(false);setNote('');setUrl('');};
  return <div className="ops"><h1>요청 자료</h1>{requests.map(r=><article className="ops-item" key={r.student.id+':'+r.id}><div className="ops-toolbar"><h2>{r.title}</h2><span className="ops-tag">{CRM_REQUEST_STATUS[r.status]}</span></div><p>{r.student.name} · {r.category} · 제출 기한 {r.dueDate}</p><p className="crm-prewrap">{r.instructions}</p><CRMRequestHistory request={r}/>{['requested','returned'].includes(r.status)&&<OpsButton icon="Reply" disabled={preview} onClick={()=>{setReply(r);setNote('');setUrl('');setError('');}}>자료 / 답변 제출</OpsButton>}</article>)}{!requests.length&&<OpsEmpty>담당자가 요청한 자료가 없습니다.</OpsEmpty>}{reply&&<PPDialog title={reply.title+' 회신'} close={close}><div className="ops"><OpsField label="자료 링크" type="url" value={url} onChange={v=>{setUrl(v);onDirty(true);}}/><OpsField label="전달 내용" type="textarea" rows={5} value={note} onChange={v=>{setNote(v);onDirty(true);}}/>{error&&<p role="alert">{error}</p>}<OpsSave run={async()=>{PP.replyToRequest(reply.student,reply.id,{note,url});if(!replyRequest)throw Error('학부모 계정으로 접속하여 회신해 주세요.');await replyRequest(reply.student.id,reply.id,{note,url});onDirty(false);setReply(null);setNote('');setUrl('');}}>검토 요청 제출</OpsSave></div></PPDialog>}</div>;
}
