function CRMBatchDialog({students,selected,user,staff,persist,data,close}){
  const [action,setAction]=useState('task'),[d,setD]=useState({title:'',date:O.today(),ownerMode:'primary',ownerId:user.id,importance:3,notes:''}),[owners,setOwners]=useState([]),[reviewed,setReviewed]=useState(false),[transferTasks,setTransferTasks]=useState(true);
  const batch=React.useRef(O.id()),targets=students.filter(s=>selected.includes(s.id));const set=(k,v)=>setD({...d,[k]:v});
  return <PPDialog title={`${targets.length}명 일괄 작업`} close={close} wide><div className="ops"><OpsField label="일괄 작업 종류" value={action} options={[["task","학생별 업무 등록"],...(user.role==='admin'?[["owners","담당자 변경"]]:[])]} onChange={v=>{setAction(v);setReviewed(false);}}/>
    <div className="crm-batch-targets">{targets.map(s=><span className="ops-tag" key={s.id}>{s.name}</span>)}</div>
    {action==='task'?<><OpsField label="일괄 업무명 *" value={d.title} onChange={v=>set('title',v)}/><div className="ops-grid"><OpsField label="일괄 업무 기한 *" type="date" value={d.date} onChange={v=>set('date',v)}/><OpsField label="배정 방식" value={d.ownerMode} options={[["primary","학생의 첫 번째 담당자"],["me","나에게 배정"]]} onChange={v=>set('ownerMode',v)}/><OpsField label="업무 중요도" value={d.importance} options={[1,2,3,4,5].map(n=>[String(n),'★'.repeat(n)])} onChange={v=>set('importance',Number(v))}/></div><OpsField label="업무 메모" type="textarea" value={d.notes} onChange={v=>set('notes',v)}/></>:<><fieldset><legend>변경할 담당자</legend>{staff.map(p=><OpsCheck key={p.id} label={p.name} value={owners.includes(p.id)} onChange={v=>setOwners(v?[...owners,p.id]:owners.filter(id=>id!==p.id))}/>)}</fieldset><p className="ops-notice">선택한 학생의 기존 담당자를 위 명단으로 교체합니다. 제외되는 컨설턴트는 해당 학생에 접근할 수 없게 됩니다. 학부모 연결은 유지됩니다.</p><OpsCheck label="제외되는 담당자의 미완료 업무도 새 첫 번째 담당자에게 인계" value={transferTasks} onChange={setTransferTasks}/><p className="ops-muted">업무 인계 대상 {targets.reduce((n,s)=>n+CRM.handoffTasks(s,owners).length,0)}건</p><OpsCheck label="학생 명단과 담당자 접근 권한 변경을 확인했습니다" value={reviewed} onChange={setReviewed}/></>}
    <OpsSave run={()=>{
      if(!targets.length||targets.length>100)throw Error('한 번에 1~100명을 선택해 주세요.');
      let next;
      if(action==='owners'){
        if(user.role!=='admin'||!owners.length||!reviewed)throw Error('담당자를 선택하고 접근 권한 변경을 확인해 주세요.');
        next=data.students.map(s=>selected.includes(s.id)?CRM.reassignOwners(s,owners,transferTasks,user):s);
      }else next=CRM.batchTasks(data.students,selected,d,user,batch.current);
      return persist({...data,students:next});
    }} onDone={close}>{action==='owners'?'담당자 변경 적용':'학생별 업무 등록'}</OpsSave>
  </div></PPDialog>;
}
function CRMDirectory({students,user,data,persist,saveWorkspace,openStudent,add}){
  const [filters,setFilters]=useState({search:'',status:'active',sort:'attention'}),[selected,setSelected]=useState([]),[modal,setModal]=useState(false),[presetName,setPresetName]=useState(''),[preset,setPreset]=useState(''),[limit,setLimit]=useState(30);
  const staff=data.staffAccounts||[],w=O.workspace(data.workspace),views=w.crmViews||[],set=(k,v)=>{setFilters({...filters,[k]:v});setLimit(30);setPreset('');setSelected([]);};
  const filtered=CRM.filterStudents(students,filters),visible=filtered.slice(0,limit),duplicates=CRM.duplicateCandidates(students);
  const select=(id,on)=>setSelected(on?[...new Set([...selected,id])]:selected.filter(x=>x!==id));
  const allSelected=visible.length>0&&visible.every(s=>selected.includes(s.id));
  return <div className="ops"><div className="ops-toolbar"><h2>학생 현황</h2><span className="ops-tag">{filtered.length}명</span><OpsButton icon="UserPlus" onClick={add}>학생 추가</OpsButton></div>
    <div className="crm-filters crm-quick-filters"><OpsField label="학생·학교·태그 검색" value={filters.search} onChange={v=>set('search',v)}/><OpsField label="관리 상태 필터" value={filters.status} options={CRM_STATUS} onChange={v=>set('status',v)}/><OpsField label="정렬" value={filters.sort} options={[["attention","관리 필요 순"],["name","학생명 순"],["end","프로그램 종료일 순"]]} onChange={v=>set('sort',v)}/></div>
    <details className="crm-filter-details"><summary>상세 필터{['owner','program','stage','attention','priority'].filter(k=>filters[k]).length>0&&` · ${['owner','program','stage','attention','priority'].filter(k=>filters[k]).length}개 적용`}</summary><div className="crm-filters"><OpsField label="담당자 필터" value={filters.owner} options={staff.map(p=>[p.id,p.name])} onChange={v=>set('owner',v)}/><OpsField label="프로그램 필터" value={filters.program} options={[...new Set(students.map(s=>s.program).filter(Boolean))]} onChange={v=>set('program',v)}/><OpsField label="Stage 필터" value={filters.stage} options={V2_STAGE_KEYS} onChange={v=>set('stage',v)}/><OpsField label="확인 사항 필터" value={filters.attention} options={[["any","확인 사항 전체"],["overdue","지연 업무"],["contact","연락 주기 경과"],["contactMissing","연락 기록 없음"],["submissions","학부모 자료 검토"],["requestReview","요청 자료 검토"],["requestOverdue","요청 자료 제출 지연"],["applicationDate","원서 마감 미확인"],["programEnd","프로그램 종료 예정/경과"]]} onChange={v=>set('attention',v)}/><OpsField label="우선순위 필터" value={filters.priority} options={[["high","우선 관리"],["standard","일반 관리"]]} onChange={v=>set('priority',v)}/><OpsButton icon="FilterX" onClick={()=>{setFilters({search:'',status:'active',sort:'attention'});setSelected([]);setPreset('');}}>필터 초기화</OpsButton></div></details>
    <details className="ops-band"><summary>내 필터 보기</summary><div className="ops-grid three"><OpsField label="저장된 필터" value={preset} options={views.map(v=>[v.id,v.name])} onChange={id=>{setPreset(id);const v=views.find(x=>x.id===id);if(v){setFilters(v.filters);setSelected([]);setLimit(30);}}}/><OpsField label="필터 이름" value={presetName} onChange={setPresetName}/><div className="ops-toolbar"><OpsSave run={async()=>{if(!presetName.trim())throw Error('필터 이름을 입력해 주세요.');if(views.length>=20)throw Error('필터는 최대 20개까지 저장할 수 있습니다.');await saveWorkspace({...w,crmViews:[...views,{id:O.id(),name:presetName.trim().slice(0,60),filters:{...filters,search:''}}]});setPresetName('');}}>현재 필터 저장</OpsSave>{preset&&<OpsSave run={async()=>{await saveWorkspace({...w,crmViews:views.filter(v=>v.id!==preset)});setPreset('');}}>선택 필터 삭제</OpsSave>}</div></div></details>
    {selected.length>0&&<div className="crm-selection"><b>{selected.length}명 선택</b><OpsButton icon="ListPlus" onClick={()=>setModal(true)}>일괄 작업</OpsButton><OpsButton icon="X" onClick={()=>setSelected([])}>선택 해제</OpsButton></div>}
    <div className="ops-table crm-students"><table className="table"><thead><tr><th><input type="checkbox" aria-label="현재 표시 학생 전체 선택" checked={allSelected} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(s=>s.id)])]:selected.filter(id=>!visible.some(s=>s.id===id)))}/></th><th>학생 / 프로그램</th><th>담당 / Stage</th><th>확인 사항</th><th>최근 연락 / 다음 미팅</th><th></th></tr></thead><tbody>{visible.map(s=>{const c=CRM.crm(s),meeting=O.operations(s).meetings.filter(m=>!m.appliedAt&&!m.cancelled&&m.date>=O.today()).sort((a,b)=>a.date.localeCompare(b.date))[0];return <tr key={s.id}><td><input type="checkbox" aria-label={`${s.name} 선택`} checked={selected.includes(s.id)} onChange={e=>select(s.id,e.target.checked)}/></td><td><CRMStudentLink student={s} openStudent={openStudent}/><p className="ops-muted">{s.program||'프로그램 미정'}<br/>{s.school||'학교 미입력'}</p><span className="ops-tag">{CRM_STATUS.find(x=>x[0]===c.status)?.[1]}</span>{c.priority==='high'&&<span className="ops-tag warn">우선 관리</span>}</td><td>{(s.owners||[]).map(id=>staff.find(p=>p.id===id)?.name).filter(Boolean).join(', ')||'담당 미지정'}<p>{V2_STAGE_KEYS.find(x=>x[0]===s.stage)?.[1]||'Stage 1'}</p><progress className="ops-progress" max="100" value={v2StageCompletion(s,s.stage||'stage1')}/><small>{v2StageCompletion(s,s.stage||'stage1')}%</small></td><td><CRMAlertBadges student={s}/></td><td><p>연락: {CRM.lastContact(s)||'기록 없음'}</p><p>미팅: {meeting?`${meeting.date} · ${meeting.title}`:'미등록'}</p>{meeting?.agenda&&<p className="ops-muted">{meeting.agenda}</p>}</td><td><OpsButton icon="ArrowRight" onClick={()=>openStudent(s)}>열기</OpsButton><OpsButton icon="Phone" onClick={()=>openStudent(s,'crm')}>연락 관리</OpsButton></td></tr>;})}</tbody></table></div>
    <div className="crm-mobile-students">{visible.map(s=><article className="ops-item" key={s.id}><div className="ops-toolbar"><OpsCheck label={`${s.name} 선택`} value={selected.includes(s.id)} onChange={v=>select(s.id,v)}/><OpsButton icon="ArrowRight" onClick={()=>openStudent(s)}>열기</OpsButton></div><p>{s.program||'프로그램 미정'} · {V2_STAGE_KEYS.find(x=>x[0]===s.stage)?.[1]||'Stage 1'}</p><p className="ops-muted">{s.school} · {(s.owners||[]).map(id=>staff.find(p=>p.id===id)?.name).filter(Boolean).join(', ')}</p><CRMAlertBadges student={s}/><p>최근 연락 {CRM.lastContact(s)||'기록 없음'}</p><OpsButton icon="Phone" onClick={()=>openStudent(s,'crm')}>연락 관리</OpsButton></article>)}</div>
    {!filtered.length&&<OpsEmpty>조건에 맞는 학생이 없습니다.</OpsEmpty>}{filtered.length>limit&&<OpsButton icon="ChevronDown" onClick={()=>setLimit(limit+30)}>30명 더 보기</OpsButton>}
    {duplicates.length>0&&<details><summary>중복 가능 학생 {duplicates.length}그룹</summary>{duplicates.map((g,i)=><div className="ops-log" key={i}>{g.map(s=><p key={s.id}><CRMStudentLink student={s} openStudent={openStudent}/> · {s.program||'프로그램 미정'}</p>)}</div>)}<p className="ops-muted">이름과 생년월일이 일치합니다. 자동 병합하거나 삭제하지 않습니다.</p></details>}
    {modal&&<CRMBatchDialog students={students} selected={selected} user={user} staff={staff} persist={persist} data={data} close={()=>{setModal(false);setSelected([]);}}/>}
  </div>;
}
function CRMAttention({students,openStudent,compact=false,ownerId=''}){
  const [kind,setKind]=useState('all');const rows=students.flatMap(s=>CRM.attention(s,undefined,ownerId).map(a=>({...a,student:s}))).filter(a=>kind==='all'?a.level>=2:kind==='allLevels'||a.key===kind).sort((a,b)=>b.level-a.level||a.student.name.localeCompare(b.student.name));
  return <section className="ops-band"><div className="ops-toolbar"><h2>지금 확인할 사항 <span className="ops-tag">{rows.length}</span></h2>{!compact&&<OpsField label="확인 목록 종류" value={kind} options={[["all","관리 필요"],["allLevels","기록 확인 포함"],["overdue","지연 업무"],["contact","정기 연락"],["submissions","학부모 자료"],["requestReview","요청 자료 회신"],["requestOverdue","요청 자료 지연"],["programEnd","프로그램 종료"],["applicationDate","원서 마감"],["soon","3일 내 마감"]]} onChange={setKind}/>}</div>{rows.slice(0,compact?6:100).map(a=><div className="crm-alert-row" key={a.student.id+':'+a.key}><span className={'ops-tag '+(a.level>=2?'warn':'')}>{a.level===3?'우선 확인':'확인'}</span><div><CRMStudentLink student={a.student} openStudent={openStudent} tab={a.tab}/><b> · {a.title}</b><p className="ops-muted">{a.detail}</p></div><OpsButton icon="ArrowRight" onClick={()=>openStudent(a.student,a.tab)}>확인하기</OpsButton></div>)}{!rows.length&&<OpsEmpty>현재 조건에 해당하는 확인 사항이 없습니다.</OpsEmpty>}</section>;
}
function CRMTaskCenter({students,data,persist,staff,user,openStudent}){
  const [filter,setFilter]=useState('pending'),[owner,setOwner]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[limit,setLimit]=useState(40),[includeClosed,setIncludeClosed]=useState(false);
  const rows=students.filter(s=>includeClosed||CRM.crm(s).status!=='completed').flatMap(O.tasks).filter(t=>(filter==='all'||filter==='done'?filter!=='done'||t.done:!t.done)&&(filter!=='overdue'||O.date(t.date)&&t.date<O.today())&&(filter!=='week'||O.days(t.date)>=0&&O.days(t.date)<=7&&O.date(t.date))&&(filter!=='undated'||!t.date)&&(!owner||(t.ownerId?t.ownerId===owner:students.find(s=>s.id===t.studentId)?.owners?.includes(owner)))&&`${t.studentName} ${t.title} ${t.context||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||Number(b.importance||3)-Number(a.importance||3));
  const save=t=>persist({...data,students:data.students.map(s=>s.id===t.studentId?{...s,...O.updateTask(s,t)}:s)});
  return <div className="ops"><div className="crm-filters"><OpsField label="업무 검색" value={query} onChange={setQuery}/><OpsField label="업무 상태 필터" value={filter} options={[["pending","미완료 전체"],["overdue","지연"],["week","7일 내 마감"],["undated","기한 미정"],["done","완료"],["all","모든 업무"]]} onChange={v=>{setFilter(v);setLimit(40);}}/><OpsField label="업무 담당자 필터" value={owner} options={staff.map(p=>[p.id,p.name])} onChange={setOwner}/></div><OpsCheck label="종료 학생 업무 포함" value={includeClosed} onChange={setIncludeClosed}/><p>{rows.length}개 업무</p><div className="ops-table"><table className="table"><thead><tr><th>학생 / 담당</th><th>업무</th><th>기한</th><th>상태</th><th></th></tr></thead><tbody>{rows.slice(0,limit).map(t=>{const st=students.find(s=>s.id===t.studentId);return <tr key={t.uid}><td><CRMStudentLink student={st} openStudent={openStudent}/><p className="ops-muted">{staff.find(p=>p.id===t.ownerId)?.name||(st.owners||[]).map(id=>staff.find(p=>p.id===id)?.name).filter(Boolean).join(', ')||'담당 미지정'}</p></td><td><b>{t.title}</b><p className="ops-muted">{t.context}</p><span>{'★'.repeat(Math.max(1,Math.min(5,Number(t.importance)||3)))}</span></td><td>{t.date||'미정'}<br/>{!t.done&&<OpsDeadline date={t.date}/>}</td><td>{t.done?'완료':'진행 중'}</td><td><OpsButton icon="Pencil" onClick={()=>setEditing(t)}>업무 수정</OpsButton><OpsSave disabled={t.statusLocked} run={()=>{if(t.key==='applicationDeadline'&&!confirm('원서 제출 상태를 변경할까요?'))return;return save({...t,done:!t.done});}}>{t.statusLocked?'결과 확정':t.done?'완료 취소':'완료 처리'}</OpsSave></td></tr>;})}</tbody></table></div>{!rows.length&&<OpsEmpty/>}{rows.length>limit&&<OpsButton icon="ChevronDown" onClick={()=>setLimit(limit+40)}>40개 더 보기</OpsButton>}{editing&&<OpsTaskEditor task={editing} staff={staff.filter(p=>p.id===user.id||students.find(s=>s.id===editing.studentId)?.owners?.includes(p.id))} save={save} close={()=>setEditing(null)}/>}</div>;
}
function CRMWorkspace({students,data,persist,user,openStudent}){
  const [tab,setTab]=useState('attention');const staff=data.staffAccounts||[],work=CRM.workload(students,staff);
  return <div className="ops"><div className="ops-toolbar"><h2>CRM 관리</h2></div><V2SubTabs tabs={[["attention","확인 목록"],["tasks","통합 업무"],...(user.role==='admin'?[["workload","담당자별 업무 현황"]]:[])]} active={tab} set={setTab}/>{tab==='attention'&&<CRMAttention students={students} openStudent={openStudent}/>} {tab==='tasks'&&<CRMTaskCenter students={students} data={data} persist={persist} staff={staff} user={user} openStudent={openStudent}/>} {tab==='workload'&&user.role==='admin'&&<section className="ops-band"><h3>담당자별 업무 현황</h3><div className="ops-table"><table className="table"><thead><tr><th>담당자</th><th>관리 학생</th><th>공동 관리 학생</th><th>미완료 업무</th><th>지연</th><th>7일 내</th><th>확인 필요 학생</th></tr></thead><tbody>{work.map(r=><tr key={r.person.id}><th>{r.person.name}</th><td>{r.students}</td><td>{r.shared}</td><td>{r.tasks}</td><td>{r.overdue}</td><td>{r.week}</td><td>{r.attention}</td></tr>)}</tbody></table></div><p className="ops-muted">종료 학생은 제외합니다. 업무 담당자가 없는 공동 관리 업무는 각 담당자의 확인 대상으로 집계됩니다.</p></section>}</div>;
}
