const MEETING_PROGRESS_OPTIONS=[['','상태 선택'],['on-track','순조로움'],['needs-attention','확인 필요'],['blocked','문제 발생'],['complete','완료']];
const MEETING_TEST_TYPES=['SSAT','PSAT','SAT','ACT','TOEFL','TOEFL Jr','IELTS','DET','ISEE','MAP'];
const MEETING_ACTIVITY_GROUPS=[['school','학교 활동'],['external','외부 활동'],['project','프로젝트']];

function MeetingSection({number,title,guide,children}){
  return <section className="meeting-section"><div className="meeting-section-head"><span>{number}</span><div><h3>{title}</h3>{guide&&<p>{guide}</p>}</div></div><div className="meeting-section-body">{children}</div></section>;
}
function MeetingNoteRows({value,onChange,label,placeholder}){
  const rows=String(value||'').split('\n').filter(Boolean).length?String(value||'').split('\n') : [''];
  const setRows=next=>onChange(next.filter((row,index)=>row.trim()||index===next.length-1).join('\n'));
  return <div className="meeting-line-list"><div className="ops-toolbar"><h4>{label}</h4><OpsButton icon="Plus" onClick={()=>setRows([...rows,''])}>행 추가</OpsButton></div>{rows.map((row,index)=><div className="meeting-line-row" key={index}><span>{index+1}</span><input className="input" aria-label={`${label} ${index+1}`} value={row} placeholder={placeholder} onChange={e=>setRows(rows.map((item,i)=>i===index?e.target.value:item))}/>{rows.length>1&&<OpsButton icon="Trash2" aria-label={`${label} ${index+1} 삭제`} onClick={()=>setRows(rows.filter((_,i)=>i!==index))}/>}</div>)}</div>;
}
function MeetingLinkedRow({title,meta,row,change,onAction,children}){
  return <article className="meeting-linked-row"><div className="meeting-linked-context"><b>{title}</b>{meta&&<span>{meta}</span>}</div>{children||<><OpsField label="진행 상태" value={row.progressStatus||''} options={MEETING_PROGRESS_OPTIONS.slice(1)} onChange={value=>change({progressStatus:value})}/><OpsField label="진행 내용" value={row.progressNote||''} onChange={value=>change({progressNote:value})}/><OpsField label="문제 상황 / 확인 필요" value={row.issue||''} onChange={value=>change({issue:value})}/></>}<OpsButton icon="ListPlus" onClick={()=>onAction(title)}>후속 할 일 추가</OpsButton></article>;
}
function MeetingAcademicRows({rows,setRows,onAction}){
  const change=(index,patch)=>setRows(rows.map((row,i)=>i===index?{...row,...patch}:row));
  return <div className="meeting-linked-block"><h4>학업 · 수강 과목 진행상황</h4>{rows.map((row,index)=><MeetingLinkedRow key={row.id} title={row.subject} meta={`${row.school||'학교 미입력'} · ${row.termLabel||'학기 미입력'}`} row={row} change={patch=>change(index,patch)} onAction={onAction}/>)}{!rows.length&&<OpsEmpty>학교/학업에서 과목을 등록하면 이곳에 자동으로 표시됩니다.</OpsEmpty>}</div>;
}
function MeetingTestRows({rows,setRows,onAction}){
  const change=(index,patch)=>setRows(rows.map((row,i)=>i===index?{...row,...patch}:row));
  const add=()=>setRows([...rows,{id:`new-test-${O.id()}`,newGoal:true,type:'',target:'',nextDate:'',progressStatus:'',progressNote:'',issue:''}]);
  return <div className="meeting-linked-block"><div className="ops-toolbar"><h4>시험 / 준비 목표</h4><OpsButton icon="Plus" onClick={add}>시험 목표 추가</OpsButton></div>{rows.map((row,index)=><MeetingLinkedRow key={row.id} title={row.type||'새 시험 목표'} meta={row.target!==''?`목표 ${row.target}`:'목표 점수 미설정'} row={row} change={patch=>change(index,patch)} onAction={onAction}><OpsField label="시험" value={row.type||''} options={MEETING_TEST_TYPES} onChange={value=>change(index,{type:value})}/><OpsField label="목표 점수" value={row.target??''} onChange={value=>change(index,{target:value})}/><OpsField label="준비 상태" value={row.progressStatus||''} options={MEETING_PROGRESS_OPTIONS.slice(1)} onChange={value=>change(index,{progressStatus:value})}/><OpsField label="준비 진행상황" value={row.progressNote||''} onChange={value=>change(index,{progressNote:value})}/><OpsField label="문제 상황" value={row.issue||''} onChange={value=>change(index,{issue:value})}/><OpsField label="다음 시험일" type="date" value={row.nextDate||''} onChange={value=>change(index,{nextDate:value})}/></MeetingLinkedRow>)}{!rows.length&&<OpsEmpty>시험 목표 또는 시험 기록을 추가해 주세요.</OpsEmpty>}</div>;
}
function MeetingActivityRows({rows,setRows,onAction}){
  const change=(id,patch)=>setRows(rows.map(row=>row.id===id?{...row,...patch}:row));
  return <div className="meeting-linked-block"><h4>활동 진행상황</h4>{MEETING_ACTIVITY_GROUPS.map(([group,label])=><section className="meeting-activity-group" key={group}><h5>{label}</h5>{rows.filter(row=>row.group===group).map(row=><MeetingLinkedRow key={row.id} title={row.name} meta={row.category} row={row} change={patch=>change(row.id,patch)} onAction={onAction}/>)}{!rows.some(row=>row.group===group)&&<p className="ops-muted">{label}에 등록된 진행 중 활동이 없습니다.</p>}</section>)}</div>;
}
function MeetingInterviewRows({rows,setRows,onAction}){
  const change=(index,patch)=>setRows(rows.map((row,i)=>i===index?{...row,...patch}:row));
  return <div className="meeting-linked-block"><h4>인터뷰</h4>{rows.map((row,index)=><MeetingLinkedRow key={row.id} title={row.school||'지원 학교'} meta={row.date||'예약일 미정'} row={row} change={patch=>change(index,patch)} onAction={onAction}><OpsField label="인터뷰 일정" type="date" value={row.date||''} onChange={value=>change(index,{date:value})}/><OpsField label="예약 상태" value={row.status||''} options={['미예약','예약 완료','준비 중','완료']} onChange={value=>change(index,{status:value})}/><OpsField label="준비 상태" value={row.prepStatus||''} options={MEETING_PROGRESS_OPTIONS.slice(1)} onChange={value=>change(index,{prepStatus:value})}/><OpsField label="진행 / 준비 기록" value={row.notes||''} onChange={value=>change(index,{notes:value})}/><OpsField label="Google Doc / 자료 링크" type="url" value={row.docUrl||''} onChange={value=>change(index,{docUrl:value})}/>{opsUrl(row.docUrl)&&<OpsLink url={row.docUrl}>인터뷰 문서 열기</OpsLink>}</MeetingLinkedRow>)}{!rows.length&&<OpsEmpty>지원 학교를 등록하면 인터뷰 항목이 자동으로 표시됩니다.</OpsEmpty>}</div>;
}
function MeetingEssayRows({rows,setRows,onAction}){
  const change=(index,patch)=>setRows(rows.map((row,i)=>i===index?{...row,...patch}:row));
  return <div className="meeting-linked-block"><h4>에세이</h4>{rows.map((row,index)=><MeetingLinkedRow key={row.id} title={`${row.school} · ${row.title}`} meta={row.prompt} row={row} change={patch=>change(index,patch)} onAction={onAction}><OpsField label="마감일" type="date" value={row.deadline||''} onChange={value=>change(index,{deadline:value})}/><OpsField label="우선순위" value={row.priority||''} options={['높음','보통','낮음']} onChange={value=>change(index,{priority:value})}/><OpsField label="진행 상태" value={row.status||''} options={OPS_STATUS} onChange={value=>change(index,{status:value})}/><OpsField label="진행 기록" value={row.progressNote||''} onChange={value=>change(index,{progressNote:value})}/><OpsField label="Google Doc / 초안 링크" type="url" value={row.docUrl||''} onChange={value=>change(index,{docUrl:value})}/>{opsUrl(row.docUrl)&&<OpsLink url={row.docUrl}>에세이 문서 열기</OpsLink>}</MeetingLinkedRow>)}{!rows.length&&<OpsEmpty>원서의 에세이 질문을 등록하면 이곳에 자동으로 표시됩니다.</OpsEmpty>}</div>;
}
function MeetingActionItems({items,setItems,staff,studentName,meetingDate}){
  const add=()=>setItems([...items,{id:O.id(),title:'',responsibleId:'student',responsibleName:studentName||'학생',dueDate:'',dueDateAuto:true,done:false,url:'',createTask:true}]);
  const change=(index,patch)=>setItems(items.map((item,i)=>i===index?{...item,...patch}:item));
  const titleChange=(index,value)=>{const current=items[index],parsed=window.PrepMeetingRecords.parseDueDate(value,meetingDate);change(index,{title:value,...((!current.dueDate||current.dueDateAuto)&&parsed?{dueDate:parsed,dueDateAuto:true}:{})});};
  const people=[['student',`${studentName||'학생'} (학생)`],...staff.map(person=>[person.id,person.name])];
  return <div className="meeting-actions"><div className="ops-toolbar"><h4>다음 미팅 전 할 일</h4><OpsButton icon="Plus" onClick={add}>할 일 추가</OpsButton></div>{items.map((item,index)=><article className="meeting-action-row" key={item.id||index}><OpsField label="할 일 / 숙제" placeholder="예: 9/21까지 초안 작성하고 제출하기" value={item.title} onChange={value=>titleChange(index,value)}/><OpsField label="담당" value={item.responsibleId||'student'} options={people} onChange={value=>change(index,{responsibleId:value,responsibleName:value==='student'?(studentName||'학생'):(staff.find(person=>person.id===value)?.name||'')})}/><OpsField label="마감일" type="date" value={item.dueDate} onChange={value=>change(index,{dueDate:value,dueDateAuto:false})}/><div className="meeting-action-options"><OpsCheck label="완료" value={item.done} onChange={value=>change(index,{done:value})}/><OpsCheck label="할 일·캘린더에 반영" value={item.createTask!==false} onChange={value=>change(index,{createTask:value})}/><OpsButton icon="Trash2" aria-label="할 일 삭제" onClick={()=>setItems(items.filter((_,i)=>i!==index))}/></div><div className="meeting-action-link"><OpsField label="자료 링크 (선택)" type="url" placeholder="https://" value={item.url} onChange={value=>change(index,{url:value})}/>{opsUrl(item.url)&&<OpsLink url={item.url}>자료 열기</OpsLink>}</div></article>)}{!items.length&&<OpsEmpty>할 일 추가를 눌러 한 줄씩 입력해 주세요. 날짜 표현을 찾으면 마감일을 자동으로 채웁니다.</OpsEmpty>}</div>;
}
function OpsMeetingEditorLinked({st,meeting,history=[],update,close,staff=[]}){
  const model=window.PrepMeetingRecords;
  const seed=model.hydrate({id:O.id(),date:O.today(),...meeting},st);if(!seed.id)seed.id=O.id();if(!seed.date)seed.date=O.today();
  const [d,setD]=useState(seed),[sourceId,setSourceId]=useState('');
  const set=(key,value)=>setD(old=>({...old,[key]:value}));
  const setRows=(key,value)=>setD(old=>({...old,[key]:value}));
  const addAction=label=>setD(old=>({...old,actionItems:[...old.actionItems,{id:O.id(),title:`${label} 후속: `,responsibleId:'student',responsibleName:st.name||'학생',dueDate:'',dueDateAuto:true,done:false,url:'',createTask:true}]}));
  const useExisting=id=>{setSourceId(id);if(!id)return;const source=history.find(item=>item.id===id);if(source)setD(model.hydrate(model.copyForNew(source,O.id(),O.today()),st));};
  const build=()=>model.payload(d,O.id);
  const saveDraft=()=>{const payload=build();if(!payload.title.trim()||!O.date(payload.date))throw Error('미팅 제목과 날짜를 확인해 주세요.');const operations=O.operations(st);return update({operations:{...operations,meetings:[payload,...operations.meetings.filter(item=>item.id!==payload.id)]}});};
  const dateChange=value=>setD(old=>({...old,date:value,...(old.autoTitle||old.title===model.formatMeetingTitle(old.date)?{title:model.formatMeetingTitle(value),autoTitle:true}:{})}));
  return <PPDialog title="미팅 기록" close={close} wide><div className="ops meeting-editor"><div className="meeting-load-existing"><OpsField label="기존 기록 불러오기" emptyLabel="기록을 선택해 새 초안으로 복제" value={sourceId} options={history.filter(item=>item.id!==d.id).map(item=>[item.id,`${item.date||'날짜 미정'} · ${item.title}`])} onChange={useExisting}/><p>원본 기록은 보존되며 새 미팅 기록으로 저장됩니다.</p></div><div className="ops-grid three"><OpsField label="미팅 제목 *" value={d.title} onChange={value=>setD(old=>({...old,title:value,autoTitle:false}))}/><OpsField label="날짜 *" type="date" value={d.date} onChange={dateChange}/><OpsField label="시각" type="time" value={d.time} onChange={value=>set('time',value)}/></div>
    <MeetingSection number="1" title="SINCE LAST MEETING" guide="지난 미팅의 약속과 실제 완료 내용을 한 항목씩 확인합니다."><MeetingNoteRows label="지난 미팅 이후" value={d.sinceLastMeeting} onChange={value=>set('sinceLastMeeting',value)} placeholder="완료한 일 또는 미완료 사유"/></MeetingSection>
    <MeetingSection number="2" title="MEETING FOCUS" guide="오늘 확인하거나 결정할 목표를 명확하게 적습니다."><OpsField label="오늘 목표" value={d.todayGoal} onChange={value=>set('todayGoal',value)}/></MeetingSection>
    <MeetingSection number="3" title="ACADEMICS" guide="등록된 학기와 과목별 진행상황, 문제 상황을 기록합니다."><MeetingAcademicRows rows={d.academicRows} setRows={value=>setRows('academicRows',value)} onAction={addAction}/></MeetingSection>
    <MeetingSection number="4" title="TESTING / PREP" guide="현재 시험 목표, 준비 진행상황과 다음 응시일을 함께 관리합니다."><MeetingTestRows rows={d.testRows} setRows={value=>setRows('testRows',value)} onAction={addAction}/></MeetingSection>
    <MeetingSection number="5" title="ACTIVITIES" guide="진행 중인 활동을 학교 활동, 외부 활동, 프로젝트로 나누어 확인합니다."><MeetingActivityRows rows={d.activityRows} setRows={value=>setRows('activityRows',value)} onAction={addAction}/></MeetingSection>
    <MeetingSection number="6" title="INTERVIEWS" guide="지원학교 인터뷰 일정, 준비 상태와 연결 문서를 확인합니다."><MeetingInterviewRows rows={d.interviewRows} setRows={value=>setRows('interviewRows',value)} onAction={addAction}/></MeetingSection>
    <MeetingSection number="7" title="ESSAYS" guide="학교별 질문, 마감, 우선순위와 Google Doc을 한곳에서 관리합니다."><MeetingEssayRows rows={d.essayRows} setRows={value=>setRows('essayRows',value)} onAction={addAction}/></MeetingSection>
    <MeetingSection number="8" title="OTHER" guide="위 분류에 포함되지 않는 내용을 한 줄씩 기록합니다."><MeetingNoteRows label="기타 사항" value={d.otherRows.map(row=>row.note).join('\n')} onChange={value=>set('otherRows',value.split('\n').map((note,index)=>({id:`other-${index+1}`,note})))} placeholder="기타 확인 사항"/></MeetingSection>
    <MeetingSection number="9" title="ACTION ITEMS / HOMEWORK" guide="자연어로 날짜를 입력하면 마감일이 자동 입력되고, 저장 시 할 일과 캘린더에 함께 표시됩니다."><MeetingActionItems items={d.actionItems} setItems={value=>set('actionItems',value)} staff={staff} studentName={st.name} meetingDate={d.date}/></MeetingSection>
    <MeetingSection number="10" title="NOTES FOR PARENTS & CONSULTANT" guide="학부모 전달 내용과 내부 메모를 분리해 기록합니다."><OpsField label="학부모 전달 요약" type="textarea" rows={6} value={d.parentSummary} onChange={value=>set('parentSummary',value)}/><OpsCheck label="학부모 공개 진행상황에 전달 요약 포함" value={d.shareWithFamily} onChange={value=>set('shareWithFamily',value)}/><OpsField label="내부 전용 메모" type="textarea" rows={4} value={d.internalNotes} onChange={value=>set('internalNotes',value)}/></MeetingSection>
    <div className="ops-sticky ops-toolbar"><OpsSave run={saveDraft} onDone={close}>임시저장 / 미팅 예약</OpsSave><OpsSave run={()=>update(O.applyMeeting(st,build()))} onDone={close}>검토 완료 · 기록과 변경사항 반영</OpsSave></div></div></PPDialog>;
}
function OpsMeetingRecordLinked({meeting,close,onReuse}){
  const d=window.PrepMeetingRecords.normalize(meeting),groups=[['학업',d.academicRows,'subject'],['시험 / 준비',d.testRows,'type'],['활동',d.activityRows,'name'],['인터뷰',d.interviewRows,'school'],['에세이',d.essayRows,'title']];
  return <PPDialog title={d.title} close={close} wide><div className="ops meeting-record-view"><p className="ops-muted">{d.date} {d.time}</p><MeetingSection number="1" title="지난 미팅 이후"><p>{d.sinceLastMeeting||'기록 없음'}</p></MeetingSection><MeetingSection number="2" title="오늘 목표"><p>{d.todayGoal||'기록 없음'}</p></MeetingSection>{groups.map(([label,rows,key],index)=><MeetingSection key={label} number={String(index+3)} title={label}>{rows.length?<div className="meeting-summary-list">{rows.map(row=><article key={row.id}><b>{row[key]}</b><span>{row.progressStatus||row.status||row.prepStatus||'상태 미입력'}</span><p>{row.progressNote||row.notes||row.issue||'진행 기록 없음'}</p></article>)}</div>:<OpsEmpty/>}</MeetingSection>)}<MeetingSection number="8" title="다음 할 일">{d.actionItems.length?<ul className="ops-list">{d.actionItems.map(item=><li key={item.id}>{item.done?'완료':'진행'} · {item.title} · {item.dueDate||'기한 미정'}</li>)}</ul>:<OpsEmpty/>}</MeetingSection><MeetingSection number="9" title="학부모 전달 / 내부 메모"><h4>학부모 전달 요약</h4><p>{d.parentSummary||'미작성'}</p><h4>내부 전용 메모</h4><p>{d.internalNotes||'미작성'}</p></MeetingSection><OpsButton icon="CopyPlus" onClick={()=>onReuse(meeting)}>이 기록을 불러와 새 미팅 작성</OpsButton></div></PPDialog>;
}
function OpsMeetingsLinked({st,update,staff=[]}){
  const [editing,setEditing]=useState(null),[view,setView]=useState(null),operations=O.operations(st),meetings=operations.meetings;
  const reuse=meeting=>{setEditing(window.PrepMeetingRecords.copyForNew(meeting,O.id(),O.today()));setView(null);};
  return <div className="ops"><div className="ops-toolbar"><h2>미팅 일정 및 기록</h2><OpsButton icon="Plus" onClick={()=>setEditing({})}>미팅 추가</OpsButton></div><p className="ops-muted">기존 학생 데이터를 불러와 진행상황만 기록합니다. 후속 할 일은 학생 업무와 캘린더에 자동 연결됩니다.</p>{meetings.map(meeting=><article className="ops-item meeting-list-item" key={meeting.id}><div className="ops-toolbar"><div><h3>{meeting.title}</h3><p>{meeting.date||'날짜 미정'} {meeting.time||''} · {meeting.todayGoal||meeting.agenda||'오늘 목표 미입력'}</p></div><span className={'ops-tag '+(meeting.appliedAt?'good':'')}>{meeting.cancelled?'취소':meeting.appliedAt?'반영 완료':'예정 / 작성 중'}</span><OpsButton icon={meeting.appliedAt?'Eye':'Pencil'} onClick={()=>meeting.appliedAt?setView(meeting):setEditing(meeting)}>{meeting.appliedAt?'기록 보기':'수정'}</OpsButton><OpsButton icon="CopyPlus" onClick={()=>reuse(meeting)}>불러오기</OpsButton>{!meeting.appliedAt&&<OpsButton icon="Trash2" onClick={()=>{if(confirm('미팅 예약과 임시 기록을 삭제할까요?'))update({operations:{...operations,meetings:meetings.filter(item=>item.id!==meeting.id)}});}}>삭제</OpsButton>}</div></article>)}{!meetings.length&&<OpsEmpty>등록된 미팅이 없습니다.</OpsEmpty>}{editing&&<OpsMeetingEditorLinked st={st} meeting={editing} history={meetings} update={update} staff={staff} close={()=>setEditing(null)}/>} {view&&<OpsMeetingRecordLinked meeting={view} close={()=>setView(null)} onReuse={reuse}/>}</div>;
}
