const MR=window.PrepMeetingRecords;
const MEETING_STATUS_OPTIONS=[['on-track','On track'],['needs-push','Needs push'],['concern','Concern']];

function OpsMeetingSection({number,title,guide,children}){
  return <section className="meeting-section"><div className="meeting-section-head"><span>{number}</span><div><h3>{title}</h3>{guide&&<p>{guide}</p>}</div></div><div className="meeting-section-body">{children}</div></section>;
}
function OpsMeetingSnapshot({label,value,onChange}){
  return <div className="meeting-snapshot-row"><b>{label}</b><div className="meeting-choice-group">{MEETING_STATUS_OPTIONS.map(([key,name])=><button type="button" key={key} aria-pressed={value===key} className={value===key?'active':''} onClick={()=>onChange(key)}>{name}</button>)}</div></div>;
}
function OpsActionItems({items,setItems,staff,studentName}){
  const add=()=>setItems([...items,{id:O.id(),title:'',responsibleId:'student',responsibleName:studentName||'학생',dueDate:'',done:false,url:'',createTask:true}]);
  const change=(index,patch)=>setItems(items.map((item,i)=>i===index?{...item,...patch}:item));
  const people=[['student',`${studentName||'학생'} (학생)`],...staff.map(person=>[person.id,person.name])];
  return <div className="meeting-actions"><div className="ops-toolbar"><h4>다음 미팅 전 실행할 일</h4><OpsButton icon="Plus" onClick={add}>할 일 추가</OpsButton></div>{items.map((item,index)=><article className="meeting-action-row" key={item.id||index}>
    <OpsField label="Task / Homework" value={item.title} onChange={value=>change(index,{title:value})}/>
    <OpsField label="Responsible" value={item.responsibleId||'student'} options={people} onChange={value=>change(index,{responsibleId:value,responsibleName:value==='student'?(studentName||'학생'):(staff.find(p=>p.id===value)?.name||'')})}/>
    <OpsField label="Due date" type="date" value={item.dueDate} onChange={value=>change(index,{dueDate:value})}/>
    <div className="meeting-action-options"><OpsCheck label="완료" value={item.done} onChange={value=>change(index,{done:value})}/><OpsCheck label="할 일에 반영" value={item.createTask!==false} onChange={value=>change(index,{createTask:value})}/><OpsButton icon="Trash2" aria-label="할 일 삭제" onClick={()=>setItems(items.filter((_,i)=>i!==index))}/></div>
    <div className="meeting-action-link"><OpsField label="자료 링크 (선택)" type="url" placeholder="https://" value={item.url} onChange={value=>change(index,{url:value})}/>{opsUrl(item.url)&&<OpsLink url={item.url}>자료 열기</OpsLink>}</div>
  </article>)}{!items.length&&<OpsEmpty>다음 미팅 전 할 일을 추가해 주세요.</OpsEmpty>}</div>;
}
function OpsMeetingEffects({st,effects,setEffects}){
  const change=(index,patch)=>setEffects(effects.map((item,i)=>i===index?{...item,...patch}:item));
  const ecs=O.rows(st.ecs,'ec');
  if(!effects.length)return null;
  return <details className="meeting-effects" open><summary>학생 정보에 함께 반영할 업데이트 {effects.length}개</summary>{effects.map((effect,index)=><article className="ops-item" key={effect.id||index}><div className="ops-toolbar"><OpsCheck label={{ec:'EC 활동',event:'일정',award:'수상'}[effect.kind]||'업데이트'} value={effect.selected!==false} onChange={value=>change(index,{selected:value})}/><OpsButton icon="Trash2" onClick={()=>setEffects(effects.filter((_,i)=>i!==index))}>삭제</OpsButton></div>{effect.kind==='ec'?<div className="ops-grid three"><OpsField label="기존 활동 연결" value={effect.targetId} options={ecs.map(item=>[item.id,item.name||'이름 미입력'])} onChange={value=>change(index,{targetId:value,name:value?ecs.find(item=>item.id===value)?.name:effect.name})}/><OpsField label="활동명" value={effect.name} onChange={value=>change(index,{name:value})}/><OpsField label="분류" value={effect.cat} options={OPS_CATEGORIES} onChange={value=>change(index,{cat:value})}/><OpsField label="주당 시간" type="number" min="0" max="168" value={effect.hours} onChange={value=>change(index,{hours:value})}/><OpsField label="역할" value={effect.position} onChange={value=>change(index,{position:value})}/><OpsField label="확인된 성과 / 기여" value={effect.impact} onChange={value=>change(index,{impact:value})}/></div>:effect.kind==='award'?<div className="ops-grid"><OpsField label="수상명" value={effect.awardName} onChange={value=>change(index,{awardName:value})}/><OpsField label="대회명" value={effect.competition} onChange={value=>change(index,{competition:value})}/><OpsField label="레벨" value={effect.level} options={['International','National','Regional/Local','School']} onChange={value=>change(index,{level:value})}/><OpsField label="수상 연월" type="month" value={effect.date} onChange={value=>change(index,{date:value})}/></div>:<div className="ops-grid"><OpsField label="일정 제목" value={effect.title} onChange={value=>change(index,{title:value})}/><OpsField label="일정 날짜" type="date" value={effect.date} onChange={value=>change(index,{date:value})}/></div>}</article>)}</details>;
}
function OpsMeetingEditorV2({st,meeting,history=[],update,close,staff=[]}){
  const initial=MR.normalize({id:O.id(),date:O.today(),...meeting});
  if(!initial.id)initial.id=O.id();
  if(!initial.date)initial.date=O.today();
  const [d,setD]=useState(initial),[sourceId,setSourceId]=useState('');
  const set=(key,value)=>setD(old=>({...old,[key]:value}));
  const setDiscussion=(key,value)=>setD(old=>({...old,discussion:{...old.discussion,[key]:value}}));
  const setSnapshot=(key,value)=>setD(old=>({...old,snapshot:{...old.snapshot,[key]:value}}));
  const useExisting=id=>{setSourceId(id);if(!id)return;const source=history.find(item=>item.id===id);if(source)setD(MR.copyForNew(source,O.id(),O.today()));};
  const build=()=>MR.payload(d,O.id);
  const saveDraft=()=>{const payload=build();if(!payload.title.trim()||!O.date(payload.date))throw Error('미팅 제목과 날짜를 확인해 주세요.');const operations=O.operations(st);return update({operations:{...operations,meetings:[payload,...operations.meetings.filter(item=>item.id!==payload.id)]}});};
  const intakeText=[d.sinceLastMeeting,d.todayGoal,...Object.values(d.discussion),d.internalNotes].filter(Boolean).join('\n\n');
  const receiveProposal=proposal=>{const rows=(proposal.rows||[]).map(row=>({...row,id:row.id||O.id(),selected:true}));const tasks=rows.filter(row=>row.kind==='task').map(row=>({id:O.id(),title:row.title||'',responsibleId:row.ownerId||'student',responsibleName:row.ownerId?(staff.find(p=>p.id===row.ownerId)?.name||''):(st.name||'학생'),dueDate:row.date||'',done:false,url:'',createTask:true}));setD(old=>({...old,actionItems:[...old.actionItems,...tasks],effects:[...old.effects,...rows.filter(row=>row.kind!=='task')]}));};
  return <PPDialog title="미팅 기록" close={close} wide><div className="ops meeting-editor">
    <div className="meeting-load-existing"><OpsField label="기존 기록 불러오기" emptyLabel="기록을 선택해 새 초안으로 복제" value={sourceId} options={history.filter(item=>item.id!==d.id).map(item=>[item.id,`${item.date||'날짜 미정'} · ${item.title}`])} onChange={useExisting}/><p>원본 기록은 보존되며 새 미팅 기록으로 저장됩니다.</p></div>
    <div className="ops-grid three"><OpsField label="미팅 제목 *" value={d.title} onChange={value=>set('title',value)}/><OpsField label="날짜 *" type="date" value={d.date} onChange={value=>set('date',value)}/><OpsField label="시각" type="time" value={d.time} onChange={value=>set('time',value)}/></div>
    <OpsMeetingSection number="1" title="SINCE LAST MEETING" guide="지난 미팅에서 정한 일과 실제 완료 내용을 비교하고, 미완료 사항과 이유를 기록합니다."><OpsField label="지난 미팅 이후" type="textarea" rows={5} value={d.sinceLastMeeting} onChange={value=>set('sinceLastMeeting',value)}/></OpsMeetingSection>
    <OpsMeetingSection number="2" title="MEETING FOCUS" guide="오늘 반드시 확인하거나 결정할 핵심 목표를 한 문장으로 정리합니다."><OpsField label="오늘 목표" type="textarea" rows={4} value={d.todayGoal} onChange={value=>set('todayGoal',value)}/></OpsMeetingSection>
    <OpsMeetingSection number="3" title="DISCUSSION NOTES & PROGRESS" guide="분야별 업데이트, 우려 사항, 결정 내용과 진행 상황을 남깁니다."><div className="meeting-discussion-grid"><OpsField label="Academics / 학업" type="textarea" rows={4} value={d.discussion.academics} onChange={value=>setDiscussion('academics',value)}/><OpsField label="Testing / Prep · 시험 / 준비" type="textarea" rows={4} value={d.discussion.testing} onChange={value=>setDiscussion('testing',value)}/><OpsField label="Activities / Interviews · 활동 / 인터뷰" type="textarea" rows={5} value={d.discussion.activities} onChange={value=>setDiscussion('activities',value)}/><OpsField label="Other / Open notes · 기타" type="textarea" rows={4} value={d.discussion.other} onChange={value=>setDiscussion('other',value)}/></div><OpsIntakeButton st={st} kind="meeting" text={intakeText} onDraft={receiveProposal}/><OpsMeetingEffects st={st} effects={d.effects} setEffects={value=>set('effects',value)}/></OpsMeetingSection>
    <OpsMeetingSection number="4" title="PROGRESS SNAPSHOT" guide="학부모와 다음 담당자가 가장 먼저 확인할 수 있도록 각 항목을 하나씩 선택합니다."><OpsMeetingSnapshot label="Effort since last meeting / 지난 미팅 이후 노력" value={d.snapshot.effort} onChange={value=>setSnapshot('effort',value)}/><OpsMeetingSnapshot label="Timeline / deadlines / 일정과 마감" value={d.snapshot.timeline} onChange={value=>setSnapshot('timeline',value)}/><OpsMeetingSnapshot label="Student engagement / 학생 참여도" value={d.snapshot.engagement} onChange={value=>setSnapshot('engagement',value)}/></OpsMeetingSection>
    <OpsMeetingSection number="5" title="ACTION ITEMS / HOMEWORK" guide="미팅을 마치기 전 담당자와 마감일을 확인합니다. 저장 시 학생의 할 일과 연결할 수 있습니다."><OpsActionItems items={d.actionItems} setItems={value=>set('actionItems',value)} staff={staff} studentName={st.name}/></OpsMeetingSection>
    <OpsMeetingSection number="6" title="NOTES FOR PARENTS & CONSULTANT" guide="학부모 전달 내용과 내부 메모를 분리해 기록합니다."><OpsField label="Summary to send parents / 학부모 전달 요약" type="textarea" rows={8} value={d.parentSummary} onChange={value=>set('parentSummary',value)}/><OpsCheck label="학부모 공개 진행상황에 전달 요약 포함" value={d.shareWithFamily} onChange={value=>set('shareWithFamily',value)}/><OpsField label="Internal only — do not share / 내부 전용 메모" type="textarea" rows={5} value={d.internalNotes} onChange={value=>set('internalNotes',value)}/></OpsMeetingSection>
    <div className="ops-sticky ops-toolbar"><OpsSave run={saveDraft} onDone={close}>임시저장 / 미팅 예약</OpsSave><OpsSave run={()=>update(O.applyMeeting(st,build()))} onDone={close}>검토 완료 · 기록과 변경사항 반영</OpsSave></div>
  </div></PPDialog>;
}
function OpsMeetingRecordV2({meeting,close,onReuse}){
  const d=MR.normalize(meeting);
  const statusName=key=>MEETING_STATUS_OPTIONS.find(item=>item[0]===key)?.[1]||'미선택';
  return <PPDialog title={d.title} close={close} wide><div className="ops meeting-record-view"><p className="ops-muted">{d.date} {d.time}</p><OpsMeetingSection number="1" title="SINCE LAST MEETING"><p>{d.sinceLastMeeting||'기록 없음'}</p></OpsMeetingSection><OpsMeetingSection number="2" title="MEETING FOCUS"><p>{d.todayGoal||'기록 없음'}</p></OpsMeetingSection><OpsMeetingSection number="3" title="DISCUSSION NOTES & PROGRESS"><dl className="meeting-record-grid"><div><dt>학업</dt><dd>{d.discussion.academics||'-'}</dd></div><div><dt>시험 / 준비</dt><dd>{d.discussion.testing||'-'}</dd></div><div><dt>활동 / 인터뷰</dt><dd>{d.discussion.activities||'-'}</dd></div><div><dt>기타</dt><dd>{d.discussion.other||'-'}</dd></div></dl></OpsMeetingSection><OpsMeetingSection number="4" title="PROGRESS SNAPSHOT"><p>노력 {statusName(d.snapshot.effort)} · 일정 {statusName(d.snapshot.timeline)} · 참여도 {statusName(d.snapshot.engagement)}</p></OpsMeetingSection><OpsMeetingSection number="5" title="ACTION ITEMS / HOMEWORK">{d.actionItems.length?<ul className="ops-list">{d.actionItems.map(item=><li key={item.id}>{item.done?'완료':'진행'} · {item.title} · {item.responsibleName||'담당 미정'} · {item.dueDate||'기한 미정'} {opsUrl(item.url)&&<OpsLink url={item.url}>자료</OpsLink>}</li>)}</ul>:<OpsEmpty/>}</OpsMeetingSection><OpsMeetingSection number="6" title="NOTES FOR PARENTS & CONSULTANT"><h4>학부모 전달 요약</h4><p>{d.parentSummary||'미작성'}</p><h4>내부 전용 메모</h4><p>{d.internalNotes||'미작성'}</p></OpsMeetingSection><OpsButton icon="CopyPlus" onClick={()=>onReuse(meeting)}>이 기록을 불러와 새 미팅 작성</OpsButton></div></PPDialog>;
}
function OpsMeetingsV2({st,update,staff=[]}){
  const [editing,setEditing]=useState(null),[view,setView]=useState(null);
  const operations=O.operations(st),meetings=operations.meetings;
  const reuse=meeting=>{setEditing(MR.copyForNew(meeting,O.id(),O.today()));setView(null);};
  return <div className="ops"><div className="ops-toolbar"><h2>미팅 일정 및 기록</h2><OpsButton icon="Plus" onClick={()=>setEditing({})}>미팅 추가</OpsButton></div><p className="ops-muted">미팅 내용을 같은 형식으로 축적하고, 이전 기록을 불러와 다음 미팅을 이어서 작성할 수 있습니다.</p>{meetings.map(meeting=><article className="ops-item meeting-list-item" key={meeting.id}><div className="ops-toolbar"><div><h3>{meeting.title}</h3><p>{meeting.date||'날짜 미정'} {meeting.time||''} · {meeting.todayGoal||meeting.agenda||'오늘 목표 미입력'}</p></div><span className={'ops-tag '+(meeting.appliedAt?'good':'')}>{meeting.cancelled?'취소':meeting.appliedAt?'반영 완료':'예정 / 작성 중'}</span><OpsButton icon={meeting.appliedAt?'Eye':'Pencil'} onClick={()=>meeting.appliedAt?setView(meeting):setEditing(meeting)}>{meeting.appliedAt?'기록 보기':'수정'}</OpsButton><OpsButton icon="CopyPlus" onClick={()=>reuse(meeting)}>불러오기</OpsButton>{!meeting.appliedAt&&<OpsButton icon="Trash2" onClick={()=>{if(confirm('미팅 예약과 임시 기록을 삭제할까요?'))update({operations:{...operations,meetings:meetings.filter(item=>item.id!==meeting.id)}});}}>삭제</OpsButton>}</div></article>)}{!meetings.length&&<OpsEmpty>등록된 미팅이 없습니다.</OpsEmpty>}{(st.stagePlans?.parentMeeting||st.stagePlans?.studentCoaching)&&<details><summary>이전 형식의 미팅 기록</summary><p style={{whiteSpace:'pre-wrap'}}>{st.stagePlans.parentMeeting}</p><p style={{whiteSpace:'pre-wrap'}}>{st.stagePlans.studentCoaching}</p></details>}{editing&&<OpsMeetingEditorV2 st={st} meeting={editing} history={meetings} update={update} staff={staff} close={()=>setEditing(null)}/>} {view&&<OpsMeetingRecordV2 meeting={view} close={()=>setView(null)} onReuse={reuse}/>}</div>;
}
