// Verified public sources. No future dates are inferred from prior-year deadlines.
window.PREP_OPERATIONS_VERIFIED_AT='2026-09-17';
window.PREP_ADMISSIONS_SEEDS={
  'Phillips Exeter Academy':{entryYear:'2027',deadline:'2027-01-15',platform:'Gateway',verifiedAt:'2026-09-17',sourceUrl:'https://exeter.edu/admissions/apply/',interviewUrl:'https://exeter.edu/tours-interviews/',interviewInstructions:'지원자 포털에서 인터뷰를 예약합니다. 공개 안내상 인터뷰 완료 기한은 1월 15일입니다. 예약 가능 시간을 포털에서 확인하세요.',requirements:[{id:'application',title:'Gateway 지원서 및 지원료'},{id:'transcript',title:'성적표'},{id:'english',title:'현재 영어 교사 추천서'},{id:'math',title:'현재 수학 교사 추천서'},{id:'school',title:'교장 또는 카운슬러 추천서'},{id:'personal',title:'인성·공동체 기여 추천서'},{id:'essay',title:'학생 에세이 및 학부모 진술서'},{id:'interview',title:'인터뷰',deadline:'2027-01-15'}],essays:[],essayNotice:'에세이 원문은 지원자 포털의 해당 지원연도 질문을 확인하여 등록하세요.'},
  'Loomis Chaffee School':{entryYear:'2027',deadline:'2027-01-15',platform:'SAO / Gateway',verifiedAt:'2026-09-17',sourceUrl:'https://www.loomischaffee.org/admission/application-process',interviewUrl:'https://www.loomischaffee.org/admission/application-process',interviewInstructions:'입학 문의 양식 작성 후 공식 지원 절차에서 인터뷰를 예약합니다.',requirements:[{id:'application',title:'지원서 및 지원료'},{id:'transcript',title:'성적표'},{id:'recommendations',title:'추천서'},{id:'interview',title:'인터뷰'},{id:'test-form',title:'시험 제출 여부 양식 (Test Optional Form)'},{id:'test',title:'제출 선택 시 공식 시험 성적 발송',deadline:'2027-02-01'}],essays:[],essayNotice:'SAO 또는 Gateway의 해당 연도 질문 확인이 필요합니다.'},
  'Northfield Mount Hermon School':{entryYear:'2027',deadline:'2027-01-15',platform:'SAO / Gateway',verifiedAt:'2026-09-17',sourceUrl:'https://www.nmhschool.org/admission/how-to-apply',interviewUrl:'https://www.nmhschool.org/admission/how-to-apply/application-checklist',interviewInstructions:'입학처 인터뷰 예약이 필요합니다. 영어가 모국어가 아닌 한국·중국 지원자는 InitialView 대상 여부를 확인하고, 마감 최소 2주 전 예약 안내에 따라 준비하세요.',requirements:[{id:'inquiry',title:'입학 문의 양식'},{id:'application',title:'SAO 또는 Gateway 지원서'},{id:'english-rec',title:'현재 영어 교사 추천서'},{id:'math-rec',title:'현재 수학 교사 추천서'},{id:'english-test',title:'영어시험 성적 또는 최근 2년 영어수업 기반 면제 승인 확인'},{id:'interview',title:'인터뷰 / 해당 시 InitialView'},{id:'transcript-check',title:'지원 포털의 성적표 제출 요건 확인'}],essays:[],essayNotice:'일반 학업시험은 선택 제출입니다. 영어시험은 별도 요건입니다. 공식 체크리스트는 TOEFL 100(구체계) 또는 5.5, DET 125, IELTS 7을 권장하며, 면제는 학교 승인을 확인하세요.'},
  'Phillips Academy Andover':{entryYear:'2027',deadline:'2027-02-01',platform:'Gateway',verifiedAt:'2026-09-17',sourceUrl:'https://www.andover.edu/Admission/',interviewUrl:'https://www.andover.edu/admission/apply',interviewInstructions:'공식 How to Apply 페이지에서 Candidate Profile 제출과 인터뷰 예약 절차를 확인하세요.',requirements:[{id:'profile',title:'Candidate Profile'},{id:'checklist',title:'지원자 포털의 해당 연도 서류·추천서 체크리스트 확인'}],essays:[],essayNotice:'공식 입학 페이지의 2027년 2월 1일 마감 확인. 서류와 에세이 원문은 해당 지원자 포털에서 추가 확인하세요.'},
  "St. Andrew's School, DE":{entryYear:'',deadline:'',platform:'SAO / Gateway',verifiedAt:'2026-09-17',sourceUrl:'https://www.standrews-de.org/admission/how-to-apply',interviewUrl:'https://www.standrews-de.org/admission/for-international-applicants',interviewInstructions:'문의 양식 제출 후 입학처에 방문 또는 온라인 인터뷰를 요청합니다. admissions@standrews-de.org / +1 302-285-4231',requirements:[{id:'application',title:'SAO 또는 Gateway 중 한 플랫폼으로 지원'},{id:'english-rec',title:'현재 영어 교사 추천서'},{id:'math-rec',title:'현재 수학 교사 추천서'},{id:'school-rec',title:'학교 관리자 추천서'},{id:'transcript',title:'성적표'},{id:'testing',title:'SSAT 또는 ISEE 공식 점수'},{id:'english-testing',title:'해당 시 TOEFL 또는 IELTS / 영어수업 학교 면제 조건 확인'}],essays:[],essayNotice:'공식 페이지는 매년 1월 15일 지원 마감, 1월 31일 서류 완료를 안내합니다. 특정 지원연도 확정 전에는 날짜를 자동 설정하지 않습니다.'}
};
window.PREP_OPPORTUNITIES=[
 {id:'amc8-2027',name:'AMC 8',category:'STEM',tags:['math','UKMT','AMC','STEM','수학'],minGrade:1,maxGrade:8,deadline:'2027-01-21',deadlineKind:'응시 가능 기간 시작',endDate:'2027-01-27',eligibility:'8학년 이하, 대회 당일 15.5세 미만. 응시 장소 및 등록 마감은 주관 시험센터에서 별도 확인해야 합니다.',url:'https://maa.org/student-programs/amc/',verifiedAt:'2026-09-17',level:'International',description:'수학 문제 해결 활동. 국제적으로 참여할 수 있다는 사실과 국제 수상 등급은 구분하며, 수상은 결과 확인 후 별도로 기록합니다.'},
 {id:'john-locke-next',name:'John Locke Global Essay Prize',category:'Academic & Intellectual',tags:['writing','essay','debate','humanities','글쓰기'],minGrade:5,maxGrade:12,deadline:'',eligibility:'2026 공지 기준 제출 마감일에 19세 미만. 다음 회차 일정·질문·연령 기준은 새 공지 확인이 필요합니다.',url:'https://www.johnlockeinstitute.com/essay-competition',verifiedAt:'2026-09-17',level:'International',description:'논제를 분석하고 근거와 반론을 구성하는 에세이 활동. 2027년 마감일은 아직 이 데이터에 확정하지 않았습니다.'},
 {id:'scholastic-2027',name:'Scholastic Art & Writing Awards',category:'Arts',tags:['art','music','writing','Arts','글쓰기','미술'],minGrade:7,maxGrade:12,deadline:'',eligibility:'7~12학년, 13세 이상. 미국·미국령·미군 기지 또는 캐나다(퀘벡 제외) 거주 조건이 있습니다. 지역별 마감일이 다릅니다.',url:'https://cms.artandwriting.org/awards/how-to-enter/',verifiedAt:'2026-09-17',level:'National',description:'미술·글쓰기 작품 포트폴리오. 국제대회로 분류하지 않으며 거주·지역 자격 확인 후 등록합니다.'}
];
