const O=window.PrepOperations;
const OPS_STATUS=['미시작','진행 중','검토 필요','완료'];
const OPS_CATEGORIES=['Sports','Music','Arts','Community Services','STEM','Debate/Speech','Journalism/Publication','Internship/Entrepreneurship','Academic & Intellectual'];
const opsUrl=url=>{try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
function OpsField({label,value,onChange,type='text',options,rows=3,emptyLabel='선택',...props}){return <label className="field"><span className="label">{label}</span>{options?<select aria-label={label} className="select" value={value??''} onChange={e=>onChange(e.target.value)} {...props}><option value="">{emptyLabel}</option>{options.map(x=>{const v=Array.isArray(x)?x[0]:x,l=Array.isArray(x)?x[1]:x;return <option key={v} value={v}>{l}</option>;})}</select>:type==='textarea'?<textarea className="input" value={value??''} rows={rows} onChange={e=>onChange(e.target.value)} {...props}/>:<input className="input" type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...props}/>}</label>;}
function OpsCheck({label,value,onChange}){return <label className="ops-check"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
function OpsButton({icon,children,...props}){return <button type="button" className="btn ghost ops-icon" {...props}>{icon&&<PPIcon name={icon} size={17}/>} {children}</button>;}
function OpsLink({url,children}){return opsUrl(url)?<a className="ops-link ops-icon" href={opsUrl(url)} target="_blank" rel="noopener noreferrer"><PPIcon name="ExternalLink" size={16}/>{children||'공식 안내'}</a>:null;}
function OpsEmpty({children}){return <div className="ops-empty">{children||'등록된 내용이 없습니다.'}</div>;}
function OpsDeadline({date}){const n=O.days(date);return <span className={'ops-tag '+(n!=null&&n<0?'warn':'')}>{n==null?'기한 미정':n===0?'오늘 마감':n<0?`${-n}일 지연`:`D-${n}`}</span>;}
function OpsSave({run,children='저장',onDone,disabled=false}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><button type="button" className="btn primary" disabled={busy||disabled} onClick={async()=>{setBusy(true);setError('');try{await run();onDone?.();}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'저장 중…':children}</button>{error&&<p role="alert" className="ops-danger">{error}</p>}</>;}
function OpsTaskEditor({task,staff=[],save,close,remove}){
 const [d,setD]=useState({...task}),application=d.key==='applicationDeadline';const set=(k,v)=>setD({...d,[k]:v});
 return <PPDialog title="할 일" close={close}><div className="ops"><OpsField label={application?'원서 제출':'할 일 *'} readOnly={application} value={d.title||d.text} onChange={v=>set('title',v)}/><div className="ops-grid"><OpsField label="마감일" type="date" value={d.date||d.deadline} onChange={v=>setD({...d,date:v,deadline:v})}/>{!application&&<><OpsField label="담당자" value={d.ownerId} options={staff.map(s=>[s.id,s.name])} onChange={v=>set('ownerId',v)}/><OpsField label="중요도" value={d.importance||3} options={[1,2,3,4,5].map(n=>[String(n),'★'.repeat(n)])} onChange={v=>set('importance',Number(v))}/></>}{!d.statusLocked&&<OpsCheck label={application?'원서 제출 완료':'완료'} value={d.done} onChange={v=>set('done',v)}/>}</div>{!application&&<><OpsField label="메모" type="textarea" value={d.notes} onChange={v=>set('notes',v)}/>{d.studentId&&<OpsCheck label="학부모 공개 진행상황에 포함" value={d.shareWithFamily} onChange={v=>set('shareWithFamily',v)}/>}</>}<div className="ops-toolbar"><OpsSave run={()=>{if(!(d.title||d.text)?.trim())throw Error('할 일을 입력해 주세요.');return save(d);}} onDone={close}/>{remove&&<OpsButton icon="Trash2" onClick={async()=>{if(confirm('이 할 일을 삭제할까요?')){try{await remove();close();}catch(e){alert(e.message);}}}}>삭제</OpsButton>}</div></div></PPDialog>;
}
function OpsEventEditor({event,save,close,remove,scope='personal'}){const [d,setD]=useState({id:O.id(),date:O.today(),time:'',title:'',visibility:'private',...event});const set=(k,v)=>setD({...d,[k]:v});return <PPDialog title="일정" close={close}><div className="ops"><OpsField label="일정 제목 *" value={d.title} onChange={v=>set('title',v)}/><div className="ops-grid"><OpsField label="날짜 *" type="date" value={d.date} onChange={v=>set('date',v)}/><OpsField label="시각 (해당 일정의 현지 시각)" type="time" value={d.time} onChange={v=>set('time',v)}/><OpsField label="시간대" value={d.timezone||'Asia/Seoul'} options={['Asia/Seoul','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Europe/London']} onChange={v=>set('timezone',v)}/>{scope==='personal'?<OpsField label="공개 범위" value={d.visibility} options={[["private","나만 보기"],["staff","직원에게 제목·일시 공개"]]} onChange={v=>set('visibility',v)}/>:scope==='team'?<OpsField label="일정 구분" value={d.category||'team'} options={[["team","회사 전체"],["marketing","마케팅"]]} onChange={v=>set('category',v)}/>:<OpsCheck label="학부모 공개 진행상황에 포함" value={d.shareWithFamily} onChange={v=>set('shareWithFamily',v)}/>}</div><OpsField label="장소 / 링크" value={d.location} onChange={v=>set('location',v)}/><OpsField label="내부 메모" type="textarea" value={d.notes} onChange={v=>set('notes',v)}/><div className="ops-toolbar"><OpsSave run={()=>{if(!d.title.trim()||!O.date(d.date))throw Error('제목과 날짜를 입력해 주세요.');return save({...d,createdAt:d.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});}} onDone={close}/>{remove&&<OpsButton icon="Trash2" onClick={async()=>{if(confirm('일정을 삭제할까요?')){try{await remove();close();}catch(e){alert(e.message);}}}}>삭제</OpsButton>}</div></div></PPDialog>;}
function OpsCalendar({events,onEvent}){const [month,setMonth]=useState(O.today().slice(0,7)),[listMode,setListMode]=useState(false),[showDone,setShowDone]=useState(false);const filtered=events.filter(e=>e.date.startsWith(month)&&(showDone||!e.done));const y=Number(month.slice(0,4)),m=Number(month.slice(5))-1,first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();const jump=n=>{const d=new Date(y,m+n,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};const row=e=><button type="button" key={e.uid||e.id} className={'ops-event '+e.source} onClick={()=>onEvent(e)}>{e.time&&<b>{e.time} </b>}{e.studentName&&`${e.studentName} · `}{e.title}{e.done?' · 완료':''}</button>;const agenda=<div>{filtered.length?filtered.map(e=><div className="ops-log" key={e.uid||e.id}><b>{e.date}</b>{row(e)}</div>):<OpsEmpty>이 달의 일정이 없습니다.</OpsEmpty>}</div>;return <section className="ops-band"><div className="ops-toolbar"><h2>캘린더</h2><OpsButton icon="ChevronLeft" aria-label="이전 달" onClick={()=>jump(-1)}/><input aria-label="캘린더 월" className="input" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)} style={{width:170}}/><OpsButton icon="ChevronRight" aria-label="다음 달" onClick={()=>jump(1)}/><OpsButton icon={listMode?'CalendarDays':'List'} onClick={()=>setListMode(!listMode)}>{listMode?'달력':'목록'}</OpsButton><OpsCheck label="완료 포함" value={showDone} onChange={setShowDone}/></div>{listMode?agenda:<><div className="ops-cal">{['일','월','화','수','목','금','토'].map(d=><div className="ops-cal-head" key={d}>{d}</div>)}{Array.from({length:first+count},(_,i)=>{const day=i-first+1,ds=day>0?`${month}-${String(day).padStart(2,'0')}`:'';return <div className={'ops-cal-cell '+(day<1?'outside':'')} key={i}>{day>0&&<><b>{day}</b>{filtered.filter(e=>e.date===ds).map(row)}</>}</div>;})}</div><div className="ops-calendar-mobile">{agenda}</div></>}</section>;}
function OpsWorkspace({data,students,user,persist,saveWorkspace,openStudent,calendarOnly=false}){
 const w=O.workspace(data.workspace),[event,setEvent]=useState(null),[task,setTask]=useState(null),[detail,setDetail]=useState(null),[schoolSearch,setSchoolSearch]=useState(''),[notice,setNotice]=useState('');
 const [team,setTeam]=useState(''),[member,setMember]=useState(''),[teamDialog,setTeamDialog]=useState(false);
 const staff=data.staffAccounts||[],members=CRM.teamMembers(students,staff,data.staffTeams,team),selectedMember=user.role==='admin'?member:'';const scope=CRM.dashboardScope(students,user.role==='admin'?team:'',selectedMember);
 const includePersonal=!team&&(!selectedMember||selectedMember===user.id),calendarWorkspace={...w,events:includePersonal?w.events:[],tasks:includePersonal?w.tasks:[]};
 const events=O.calendar(scope,data.schools||[],calendarWorkspace,data.sharedCalendar||[],data.teamEvents||[]).filter(e=>e.source==='task'?CRM.taskForOwner(e,scope.find(s=>s.id===e.studentId)||{},selectedMember):e.source==='staff'?(!selectedMember||e.ownerId===selectedMember)&&(!team||members.some(p=>p.id===e.ownerId)):e.source==='school'&&team?scope.some(s=>s.school===e.schoolName):true);
 const allTasks=[...scope.flatMap(s=>O.tasks(s).filter(t=>CRM.taskForOwner(t,s,selectedMember))),...(includePersonal?w.tasks:[]).map(t=>({...t,key:'personal',studentName:'개인 업무',date:t.date||t.deadline}))];
 const pending=allTasks.filter(t=>!t.done),overdue=pending.filter(t=>O.days(t.date)!=null&&O.days(t.date)<0),week=pending.filter(t=>O.days(t.date)!=null&&O.days(t.date)>=0&&O.days(t.date)<=7),undated=pending.filter(t=>!t.date);
 const updates=scope.flatMap(s=>[...O.operations(s).updates,...(s.parentPortal?.submissions||[]).filter(x=>x.status==='submitted').map(x=>({id:x.id,at:x.submittedAt,title:'학부모 자료 검토 대기'}))].map(u=>({...u,student:s}))).sort((a,b)=>String(b.at).localeCompare(String(a.at)));
 const sw=async p=>{setNotice('');try{await saveWorkspace(p);}catch(e){setNotice(e.message);throw e;}};
 const sub=(key,value)=>sw({...w,subscriptions:{...w.subscriptions,[key]:value}}).catch(()=>{});
 const editStudent=(sid,patch)=>persist({...data,students:data.students.map(s=>s.id===sid?{...s,...patch}:s)});
 const taskSave=t=>{if(!t.studentId)return sw({...w,tasks:[...w.tasks.filter(x=>x.id!==t.id),t]});const st=students.find(s=>s.id===t.studentId);return editStudent(st.id,O.updateTask(st,t));};
 const onEvent=e=>{if(e.source==='material')openStudent(students.find(s=>s.id===e.studentId),'requests');else if(e.source==='personal')setEvent({scope:'personal',value:e});else if(e.source==='personalTask')setTask({...e,key:'personal'});else if(e.source==='task')setTask(e);else if(e.source==='student')setEvent({scope:'student',value:e});else if(['team','marketing'].includes(e.source)&&user.role==='admin')setEvent({scope:'team',value:e});else setDetail(e);};
 const eventSave=async d=>{if(event.scope==='personal')return sw({...w,events:[...w.events.filter(e=>e.id!==d.id),d]});if(event.scope==='team')return persist({...data,teamEvents:[...O.rows(data.teamEvents,'team').filter(e=>e.id!==d.id),d]});const st=students.find(s=>s.id===d.studentId);return editStudent(st.id,{calendarEvents:[...O.rows(st.calendarEvents,'calendar').filter(e=>e.id!==d.id),d]});};
 const eventRemove=async()=>{const d=event.value;if(event.scope==='personal')return sw({...w,events:w.events.filter(e=>e.id!==d.id)});if(event.scope==='team')return persist({...data,teamEvents:O.rows(data.teamEvents,'team').filter(e=>e.id!==d.id)});const st=students.find(s=>s.id===d.studentId);return editStudent(st.id,{calendarEvents:O.rows(st.calendarEvents,'calendar').filter(e=>e.id!==d.id)});};
 const taskList=(title,items)=><section className="ops-band"><h2>{title} <span className="ops-tag">{items.length}</span></h2>{items.length?<div className="ops-table"><table className="table"><thead><tr><th>학생 / 담당</th><th>할 일</th><th>기한</th><th>중요도</th><th></th></tr></thead><tbody>{items.map(t=><tr key={t.uid||('me'+t.key+t.id)}><td>{t.studentName}<br/><span className="ops-muted">{(data.staffAccounts||[]).find(s=>s.id===t.ownerId)?.name||(students.find(s=>s.id===t.studentId)?.owners||[]).map(id=>(data.staffAccounts||[]).find(a=>a.id===id)?.name).filter(Boolean).join(', ')||(t.studentId?'담당 미지정':user.name)}</span></td><td>{t.context&&<span className="ops-muted">{t.context}<br/></span>}{t.title}</td><td>{t.date||'미정'}<br/><OpsDeadline date={t.date}/></td><td>{'★'.repeat(Math.min(5,Math.max(1,Number(t.importance)||3)))}</td><td><OpsButton icon="Pencil" onClick={()=>setTask(t)}>수정</OpsButton></td></tr>)}</tbody></table></div>:<OpsEmpty/>}</section>;
 return <div className="ops ops-workspace"><div className="ops-toolbar"><h2>{calendarOnly?'일정 관리':`${user.name}님의 업무`}</h2><OpsButton icon="Plus" onClick={()=>setTask({id:O.id(),title:'',date:O.today(),key:'personal',importance:3})}>개인 할 일</OpsButton><OpsButton icon="CalendarPlus" onClick={()=>setEvent({scope:'personal',value:{}})}>개인 일정</OpsButton>{user.role==='admin'&&<OpsButton icon="Users" onClick={()=>setEvent({scope:'team',value:{category:'team'}})}>회사 / 마케팅 일정</OpsButton>}</div>{user.role==='admin'&&<div className="ops-team-filter"><OpsField label="팀" emptyLabel="전체 팀" value={team} options={CRM.teams} onChange={v=>{setTeam(v);setMember('');}}/><OpsField label="팀원" emptyLabel="전체 담당자" value={member} options={members.map(p=>[p.id,p.name])} onChange={setMember}/><OpsButton icon="UsersRound" onClick={()=>setTeamDialog(true)}>팀 구성</OpsButton></div>}{notice&&<p role="alert">{notice}</p>}{!calendarOnly&&<><CRMAttention compact ownerId={selectedMember} students={scope} openStudent={openStudent}/>{taskList('기한이 지난 업무',overdue)}{taskList('이번 주 할 일',week)}{undated.length>0&&<details><summary>기한 미정 업무 {undated.length}개</summary>{taskList('기한 설정 필요',undated)}</details>}</>}
 <details className="ops-band"><summary>캘린더 구독</summary><div className="ops-subscriptions"><fieldset><legend>기본 일정</legend><p className="ops-muted">담당 학생 일정·할 일·미팅·목표 마일스톤</p><OpsCheck label="회사 전체 일정" value={w.subscriptions.team} onChange={v=>sub('team',v)}/><OpsCheck label="마케팅 일정" value={w.subscriptions.marketing} onChange={v=>sub('marketing',v)}/></fieldset><fieldset><legend>학교 학사일정</legend><OpsField label="학교 검색" value={schoolSearch} onChange={setSchoolSearch}/><div className="ops-scroll">{(data.schools||[]).filter(s=>s.name.toLowerCase().includes(schoolSearch.toLowerCase())).map(s=><OpsCheck key={s.name} label={s.name} value={w.subscriptions.schoolIds.includes(s.name)} onChange={v=>sub('schoolIds',v?[...w.subscriptions.schoolIds,s.name]:w.subscriptions.schoolIds.filter(x=>x!==s.name))}/>)}</div></fieldset><fieldset><legend>직원 공개 일정</legend>{(data.staffAccounts||[]).filter(s=>s.id!==user.id).map(s=><OpsCheck key={s.id} label={s.name} value={w.subscriptions.staffIds.includes(s.id)} onChange={v=>sub('staffIds',v?[...w.subscriptions.staffIds,s.id]:w.subscriptions.staffIds.filter(x=>x!==s.id))}/>)}</fieldset></div></details>
 <OpsCalendar events={events} onEvent={onEvent}/>{!calendarOnly&&<section className="ops-band"><div className="ops-toolbar"><h2>업무 업데이트</h2><OpsSave run={()=>sw({...w,readAt:new Date().toISOString()})}>모두 확인</OpsSave></div>{updates.slice(0,30).map(u=><div className="ops-log" key={u.student.id+u.id}><b>{u.student.name} · {u.title}</b><p>{u.detail}</p><span className="ops-muted">{ppTime(u.at)}</span> <OpsButton icon="ArrowRight" onClick={()=>openStudent(u.student)}>학생 열기</OpsButton></div>)}{!updates.length&&<OpsEmpty/>}</section>}
 {task&&<OpsTaskEditor task={task} staff={data.staffAccounts} close={()=>setTask(null)} save={taskSave} remove={task.studentId?undefined:()=>sw({...w,tasks:w.tasks.filter(t=>t.id!==task.id)})}/>}{event&&<OpsEventEditor event={event.value} scope={event.scope} close={()=>setEvent(null)} save={eventSave} remove={event.value.id?eventRemove:undefined}/>}{detail&&<PPDialog title={detail.title} close={()=>setDetail(null)}><p>{detail.date} {detail.time} {detail.timezone||''}</p><p>{detail.studentName||detail.ownerName}</p>{detail.notes&&<p>{detail.notes}</p>}{detail.studentId&&<OpsButton icon="ArrowRight" onClick={()=>{openStudent(students.find(s=>s.id===detail.studentId));setDetail(null);}}>학생 상세</OpsButton>}</PPDialog>}{teamDialog&&user.role==='admin'&&<OpsTeamManager data={data} persist={persist} close={()=>setTeamDialog(false)}/>}</div>;
}
function OpsStudents({students,user,add,openStudent}){const [q,setQ]=useState(''),[filter,setFilter]=useState('all');const filtered=students.filter(s=>`${s.name} ${s.en||''} ${s.program||''}`.toLowerCase().includes(q.toLowerCase())).filter(s=>filter!=='overdue'||O.tasks(s).some(t=>!t.done&&O.days(t.date)!=null&&O.days(t.date)<0));return <div className="ops"><div className="ops-toolbar"><h2>학생 현황</h2><OpsButton icon="UserPlus" onClick={add}>학생 추가</OpsButton></div><div className="ops-grid"><OpsField label="학생 / 프로그램 검색" value={q} onChange={setQ}/><OpsField label="표시" value={filter} options={[["all","전체 담당 학생"],["overdue","지연 업무가 있는 학생"]]} onChange={setFilter}/></div><div className="ops-grid">{filtered.map(s=>{const ts=O.tasks(s).filter(t=>!t.done),late=ts.filter(t=>O.days(t.date)!=null&&O.days(t.date)<0);const meeting=O.operations(s).meetings.filter(m=>m.date>=O.today()&&!m.cancelled&&!m.appliedAt).sort((a,b)=>a.date.localeCompare(b.date))[0];return <article className={'ops-item '+(late.length?'overdue':'')} key={s.id}><div className="ops-toolbar"><h3>{s.name||'신규 학생'}</h3><OpsButton icon="ArrowRight" onClick={()=>openStudent(s)}>열기</OpsButton></div><p>{s.program||'프로그램 미정'} · {V2_STAGE_KEYS.find(x=>x[0]===s.stage)?.[1]||'학생 분석'}</p><progress className="ops-progress" max="100" value={v2StageCompletion(s,s.stage||'stage1')}/><p className="ops-muted">입력 진행 {v2StageCompletion(s,s.stage||'stage1')}% · {s.school||'학교 미입력'}</p><p><b>다음 미팅</b> {meeting?`${meeting.date} ${meeting.time||''} · ${meeting.title}`:'미등록'}</p>{meeting?.agenda&&<p><b>확인할 어젠다</b> {meeting.agenda}</p>}<div className="ops-inline"><span className="ops-tag">남은 업무 {ts.length}</span>{late.length>0&&<span className="ops-tag warn">지연 {late.length}</span>}</div><ul className="ops-list">{[...ts].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).slice(0,3).map(t=><li key={t.uid}>{t.title} · {t.date||'기한 미정'}</li>)}</ul></article>;})}</div>{!filtered.length&&<OpsEmpty>표시할 학생이 없습니다.</OpsEmpty>}</div>;}
