function OpsCatalogue({data,persist}) {
 const records=data.opportunities||window.PREP_OPPORTUNITIES||[];
 const [q,setQ]=useState(''),[editing,setEditing]=useState(null);
 const save=d=>persist({...data,opportunities:[...records.filter(x=>x.id!==d.id),d]});
 return <div className="ops"><div className="ops-toolbar"><h2>대회 / 활동 데이터</h2><OpsButton icon="Plus" onClick={()=>setEditing({id:O.id(),name:'',category:'Academic & Intellectual',tags:[],active:true})}>대회 추가</OpsButton></div><OpsField label="대회 검색" value={q} onChange={setQ}/><div className="ops-grid">{records.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).map(x=><article className="ops-item" key={x.id}><div className="ops-toolbar"><h3>{x.name}</h3><OpsButton icon="Pencil" onClick={()=>setEditing(x)}>수정</OpsButton></div><p>{x.category} · {x.active===false?'비공개':'추천 목록 공개'}</p><p>{x.eligibility}</p><p className="ops-muted">확인일 {x.verifiedAt||'미확인'} · {x.deadlineKind||'마감일'} {x.deadline||'확인 필요'}</p><OpsLink url={x.url}/></article>)}</div>{editing&&<OpsCatalogueEditor value={editing} save={save} close={()=>setEditing(null)}/>}</div>;
}
function OpsCatalogueEditor({value,save,close}) {
 const [d,setD]=useState(O.clone(value)),[tags,setTags]=useState((value.tags||[]).join(', '));const set=(k,v)=>setD({...d,[k]:v});
 return <PPDialog title="대회 / 활동 편집" close={close} wide><div className="ops"><div className="ops-grid"><OpsField label="대회명 *" value={d.name} onChange={v=>set('name',v)}/><OpsField label="분류 *" value={d.category} options={OPS_CATEGORIES} onChange={v=>set('category',v)}/><OpsField label="최저 학년" value={d.minGrade} options={Array.from({length:12},(_,i)=>[String(i+1),`${i+1}학년`])} onChange={v=>set('minGrade',v)}/><OpsField label="최고 학년" value={d.maxGrade} options={Array.from({length:12},(_,i)=>[String(i+1),`${i+1}학년`])} onChange={v=>set('maxGrade',v)}/><OpsField label="날짜 의미" value={d.deadlineKind||'등록 마감'} options={['등록 마감','제출 마감','시험 시작일','행사 시작일']} onChange={v=>set('deadlineKind',v)}/><OpsField label="공식 확인된 날짜" type="date" value={d.deadline} onChange={v=>set('deadline',v)}/><OpsField label="공식 안내 URL *" type="url" value={d.url} onChange={v=>set('url',v)}/><OpsField label="자료 확인일 *" type="date" value={d.verifiedAt} onChange={v=>set('verifiedAt',v)}/></div><OpsField label="참가 자격 / 지역·나이·선발 조건 *" type="textarea" value={d.eligibility} onChange={v=>set('eligibility',v)}/><OpsField label="활동 설명 / 준비 방향" type="textarea" value={d.description} onChange={v=>set('description',v)}/><OpsField label="연결 키워드 (쉼표로 구분)" value={tags} onChange={setTags}/><OpsCheck label="추천 목록에 공개" value={d.active!==false} onChange={v=>set('active',v)}/><OpsSave run={()=>{if(!d.name.trim()||!d.category||!d.eligibility?.trim()||!opsUrl(d.url)||!O.date(d.verifiedAt))throw Error('대회명·분류·자격·공식 URL·확인일을 확인해 주세요.');if(d.minGrade&&d.maxGrade&&Number(d.minGrade)>Number(d.maxGrade))throw Error('학년 범위를 확인해 주세요.');return save({...d,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)});}} onDone={close}/></div></PPDialog>;
}
