const PREP_SCHOOL_NAMES=["Phillips Exeter Academy","Phillips Academy Andover","Groton School","Hotchkiss School","St. Paul's School","Lawrenceville School","Choate Rosemary Hall","Deerfield Academy","St. Andrew's School, DE","Middlesex School","Loomis Chaffee School","Peddie School","Milton Academy","Taft School","Thacher School","Episcopal High School","St. Mark's School","Cate School","Mercersburg Academy","Blair Academy","Lake Forest Academy","Concord Academy","The Madeira School","Woodberry Forest School","Hill School","Suffield Academy","Kent School","Miss Porter's School","Culver Academies","Berkshire School","Webb Schools","St. Stephen's Episcopal School","Northfield Mount Hermon School","Iolani School","Brooks School","Western Reserve Academy","Emma Willard School","St. George's School","Georgetown Preparatory School","Indian Springs School","Cushing Academy","Frederick Gunn School","Pomfret School","Stevenson School","The Pennington School","Williston Northampton School","Westminster School","Stony Brook School","Athenian School","Dana Hall School","Annie Wright Schools","George School","The Masters Schools","Oregon Episcopal School","Santa Catalina School, Monterey","Westtown School","Saint Andrew's School, FL","Hun School of Princeton","Woodside Priory School","The Governor's Academy","Chatham Hall School","Fountain Valley School","Saint James School","Avon Old Farms School","San Domenico School","Westover School","Grier School","Miss Hall's School","Salisbury School","Cambridge School of Weston","Portsmouth Abbey School","Tabor Academy","McCallie School","Ethel Walker","Linden Hall School","Kimball Union Academy","Canterbury School","Rabun Gap-Nacoochee School","St. Anne's-Belfield School","Holderness School","Garrison Forest School","Virginia Episcopal School","Wyoming Seminary College","Villanova Preparatory School, Ojai","Cheshire Academy","Baylor School","Millbrook School","Worcestor Academy","Asheville School","Church Farm School","Shattuck-St. Mary School","Wilbraham & Monson Academy","Colorado Rocky Mountain School","Gould Academy","Dunn School, Los Olivos","The New Hampton School","Proctor Academy","Marianapolis Prep School","Tilton School","Applewild School","Bement School","Cardigan Mountain School","Eaglebrook School","Fay School","Fessenden School","Hillside School","Indian Mountain School","Rectory School","Rumsey Hall School","Belmont Hill School","Buckingham Browne & Nichols Upper School","Noble & Greenough School"];
const PREP_SCHOOL_OVERRIDES={
"Phillips Exeter Academy":{state:"NH",region:"Northeast",town:"Exeter",boarding:.8,intl:.18,yesRank:1,nicheRank:3,accept:10,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.exeter.edu"},
"Phillips Academy Andover":{state:"MA",region:"Northeast",town:"Andover",boarding:.75,intl:.12,yesRank:2,nicheRank:2,accept:13,ssat:96,gateway:"True",deadline:"2026-02-01",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.andover.edu"},
"Choate Rosemary Hall":{state:"CT",region:"Northeast",town:"Wallingford",boarding:.75,intl:.2,yesRank:3,nicheRank:4,accept:16,ssat:96,gateway:"True",deadline:"2026-01-15",website:"https://www.choate.edu"},
"Groton School":{state:"MA",region:"Northeast",town:"Groton",boarding:.85,intl:.22,yesRank:4,nicheRank:1,accept:9,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.groton.org"},
"Hotchkiss School":{state:"CT",region:"Northeast",town:"Lakeville",boarding:.95,intl:.16,yesRank:5,nicheRank:5,accept:18,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.hotchkiss.org"},
"Lawrenceville School":{state:"NJ",region:"Mideast",town:"Lawrenceville",boarding:.7,intl:.22,yesRank:6,nicheRank:7,accept:19,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.lawrenceville.org"},
"St. Paul's School":{state:"NH",region:"Northeast",town:"Concord",boarding:1,intl:.2,yesRank:7,nicheRank:6,accept:12,ssat:96,gateway:"True",deadline:"2026-01-15",website:"https://www.sps.edu"},
"Deerfield Academy":{state:"MA",region:"Northeast",town:"Deerfield",boarding:.85,intl:.12,yesRank:8,nicheRank:14,accept:15,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://deerfield.edu"},
"Loomis Chaffee School":{state:"CT",region:"Northeast",town:"Windsor",boarding:.7,intl:.22,yesRank:9,nicheRank:10,accept:20,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.loomischaffee.org"},
"Middlesex School":{state:"MA",region:"Northeast",town:"Concord",boarding:.75,intl:.15,yesRank:10,nicheRank:17,accept:18,ssat:96,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.mxschool.edu"},
"St. Andrew's School, DE":{state:"DE",region:"Mideast",town:"Middletown",boarding:1,intl:.2,yesRank:11,nicheRank:15,accept:25,ssat:92,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.standrews-de.org"},
"Milton Academy":{state:"MA",region:"Northeast",town:"Milton",boarding:.5,intl:.15,yesRank:12,nicheRank:22,accept:25,ssat:92,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.milton.edu"},
"Taft School":{state:"CT",region:"Northeast",town:"Watertown",boarding:.75,intl:.2,yesRank:14,nicheRank:23,accept:25,ssat:92,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.taftschool.org"},
"Thacher School":{state:"CA",region:"West Coast",town:"Ojai",boarding:1,intl:.12,yesRank:12,nicheRank:18,accept:25,ssat:92,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.thacher.org"},
"Peddie School":{state:"NJ",region:"Mideast",town:"Hightstown",boarding:.75,intl:.22,yesRank:19,nicheRank:61,accept:25,ssat:92,gateway:"True",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"https://www.peddie.org"},
"Indian Mountain School":{state:"CT",region:"Northeast",town:"Lakeville",accept:40,ssat:88,programs:"Junior boarding, academics, athletics, arts, advisory"},
"Fessenden School":{state:"MA",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, boys education, athletics, arts"},
"Eaglebrook School":{state:"MA",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, boys education, athletics, leadership"},
"Fay School":{state:"MA",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, academics, student life"},
"Hillside School":{state:"MA",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, boys education, student support"},
"Rectory School":{state:"CT",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, academics, student support"},
"Rumsey Hall School":{state:"CT",region:"Northeast",accept:40,ssat:88,programs:"Junior boarding, academics, athletics"}
};
window.PREP_SCHOOLS=PREP_SCHOOL_NAMES.map((name,i)=>{
  const rank=i+1;
  const base={name,state:"",region:"",town:"",boarding:"",intl:"",yesRank:rank,nicheRank:"",accept:rank<=10?12:rank<=40?25:40,ssat:rank<=10?96:rank<=30?92:88,gateway:"",deadline:"2026-01-15",resultsDate:"2026-03-10",enrollmentDate:"2026-04-10",website:"",programs:"STEM, humanities, leadership, athletics, arts",sports:"Sports by season, varsity/JV options, strength and conditioning",arts:"Visual arts, music, theater, clubs, student leadership",fit:"Academic fit, boarding readiness, EC depth, interview maturity",risk:"Admission selectivity, testing gap, incomplete school-specific story",interview:"Why boarding, community contribution, academic curiosity, EC ownership",calendar:[]};
  const s={...base,...(PREP_SCHOOL_OVERRIDES[name]||{})};
  s.calendar=["deadline","resultsDate","enrollmentDate"].filter(k=>s[k]).map(k=>({date:s[k],title:k==="deadline"?"Application Deadline":k==="resultsDate"?"Decision Release":"Enrollment Reply",type:"Admissions",notes:""}));
  return s;
});
